### ISSUE TITLE
Shared layouts demo transition glitch with framer-motion@v2.6.3 it does work with framer-motion@v2.0.0

### ISSUE THREAD

**Issue by jeroenbraspenning** [framer/motion#738] opened 2020-08-27 14:33 UTC
I tried to use the framer-motion-2-animating-shared-layouts demo with the latest version of framer-motion@2.6.3 although it works fine with version @2.0.0 it glitches when closing the "cards" on @2.6.3. It seems like there is a mismatch in the opposing transitions because i briefly see a stretched card.

**Sandbox**
[https://codesandbox.io/s/framer-motion-2-animating-shared-layouts-forked-9lq7d?file=/src/App.js](url)

**To reproduce**
1. Click the top card
2. Close the top card
3. See the stretch glitch of the card you're closing

This happens on the browsers i tried. Chrome, Safari, Edge

**Comment by jeroenbraspenning** [comment] 2020-08-27 14:37
Some extra information:

I tried with some different framer-motion versions and the problem appears from version 2.3.0 forward.
The last working version is 2.2.0.

**Comment by AegisToast** [comment] 2020-08-27 23:40
I've been having issues with this as well, and can confirm that the issue is present in the sandbox that you shared.

In my testing, I'm seeing this jitter all the way back to 2.1.4. It's less frequent than in the more recent builds, but still happens once every 5-6 times I close one of the cards.

In versions 2.1.2 and 2.1.3 there is a very similar issue, but the jitter is in the other direction (shrinks briefly instead of stretching briefly).

Version 2.1.0 is the newest version where I can't replicate the issue in any form.

**Comment by InventingWithMonster** [comment] 2020-09-29 09:41
I'm closing this as I can't replicate in `2.7.6` but pleas reopen if you're still seeing this.

**Closed** 2021-02-23 09:07 UTC
Labels: bug
