### ISSUE TITLE
[BUG] reducing bundle size

### ISSUE THREAD

**Issue by ardaerzin** [framer/motion#861] opened 2020-11-19 15:52 UTC
**1. Read the [FAQs](#faqs) 👇**

yup

**2. Describe the bug**

reducing bundle size is not working as written on [api documentation](https://www.framer.com/api/motion/guide-reduce-bundle-size/#dynamic-feature-loading-(experimental))

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[here](https://github.com/ardaerzin/framer-motion-next/tree/master) you can find the repo I created. there are 2 branches. master has no framer-motion whereas with-motion has, well, framer-motion code added.

**4. Steps to reproduce**

1. `yarn && yarn build` for each branch.
2. nextjs build output then shows the initial js load.

**5. Expected behavior**

from [framer-motion api](https://www.framer.com/api/motion/guide-reduce-bundle-size/#dynamic-feature-loading-(experimental)) page:

> For example, if you are only importing AnimatePresence and usePresence to implement your own exit animations with CSS, you'd only add 1.4kb to your bundle.

however the bundle size difference between 2 branches is ~ **29kb**

**6. Video or screenshots**

can be found in public folder inside provided repo. 

**7. Environment details**

dont know if this changes anything, but I am on macos 11.1 Beta (20C5048k).

**Comment by TheSonOfThomp** [comment] 2020-12-07 17:35
Wanted to pull this package into my current project, but at ~30kB I can't justify it. Hopefully this is resolved soon.

![With Motion](https://user-images.githubusercontent.com/2414030/101384551-93b8c680-3888-11eb-93db-dc5a8f69d323.png)
![Without Motion](https://user-images.githubusercontent.com/2414030/101384552-94515d00-3888-11eb-8139-975645dd949f.png)

**Comment by mattgperry** [comment] 2021-02-20 09:16
Dupe of https://github.com/framer/motion/issues/254

**Closed by mattgperry** 2021-02-20 09:16 UTC
Labels: bug
