### ISSUE TITLE
[FEATURE] onAnimationRepeatCompleted

### ISSUE THREAD

**Issue by EvanPurkhiser** [framer/motion#891] opened 2020-12-14 05:46 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to create an 'infinite sliding window' for a list of elements, so I have a frame that animates left infinitely, at the end of each movement it updates the list of elements by rotating the array one element and resetting the x position, thus creating the 'infinite sliding window' effect

The problem is the `onAnimationCompleted` event does not fire after each animation iteration.

**Describe the solution you'd like**
Would be nice if there was a `onAnimationRepeatCompleted` that triggered at the end of each loop iteration.

**Comment by EvanPurkhiser** [comment] 2020-12-17 10:45
Realized I could use the useAnimation hook to get access to the onRepeat callback.

**Comment by mattgperry** [comment] 2021-03-01 13:50
Dupe of https://github.com/framer/motion/issues/519

**Closed by mattgperry** 2021-03-01 13:50 UTC
Labels: feature

**Comment by AnyaDroz** [comment] 2024-05-25 18:48
Hello! Please could someone help me understand how to access the onRepeat() callback - it's not working for me, and when I did into the code I cant see that it still exists in the library. I'm struggling to create a callback at the start of an infinitely looping animation, I've tried using onUpdate but the motion value log shows it is never quite the original value, but a decimal -> please help, thank you

**Comment by Roodbaraky** [comment] 2024-06-27 20:37
> Hello! Please could someone help me understand how to access the onRepeat() callback - it's not working for me, and when I did into the code I cant see that it still exists in the library. I'm struggling to create a callback at the start of an infinitely looping animation, I've tried using onUpdate but the motion value log shows it is never quite the original value, but a decimal -> please help, thank you

Did you get this resolved Anya? I'd really appreciate your help, facing a very similar issue.

**Comment by AnyaDroz** [comment] 2024-06-28 07:49
Hey! - the only way I could achieve these infinite animations was using sequences and the Animation Controls within a hook triggered by a state change in this example when my cards are remapped to the array > https://codesandbox.io/p/sandbox/framer-infinite-card-carousel-t25p7w?file=%2Fsrc%2Findex.js
I have quite a few sandboxes with experiments around infinite looping - hope this helps. Thanks!

**Comment by Roodbaraky** [comment] 2024-06-28 08:06
> Hey! - the only way I could achieve these infinite animations was using sequences and the Animation Controls within a hook triggered by a state change in this example when my cards are remapped to the array > https://codesandbox.io/p/sandbox/framer-infinite-card-carousel-t25p7w?file=%2Fsrc%2Findex.js I have quite a few sandboxes with experiments around infinite looping - hope this helps. Thanks!

Interesting, thanks. It's quite a different use case. I was fine with the "repeat: infinite" or X amount of times, but I wanted a callback to fire at every loop, which one might intuit is what onRepeat should achieve - it doesn't seem to do anything and there's no mention in the current docs afaik.

I've gotten around it by not using repeat at all and just executing the animation function in a loop, where I can execute a cb with each iteration. Thank you for this though, I will keep it in mind should I need to do anything like a carousel or shuffle.
