### ISSUE TITLE
Failed to compile when import motion

### ISSUE THREAD

**Issue by HubertRyanOfficial** [framer/motion#1820] opened 2022-12-10 23:45 UTC
Hey guys, I've been having this error when I import motion on any react component. How can we fix that?

Failed to compile.

./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)

--

React 17 & 18

**Comment by mattgperry** [comment] 2022-12-12 08:59
Dupe of https://github.com/framer/motion/issues/1525

**Closed by mattgperry** 2022-12-12 08:59 UTC
Labels: bug
