### ISSUE TITLE
[BUG] Animation lag after updating from v10x to 11x

### ISSUE THREAD

**Issue by rnnyrk** [framer/motion#2582] opened 2024-03-21 10:14 UTC
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

After updating to the latest framer motion the mask animation on mouse position is super laggy

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/p/devbox/framer-motion-animation-lag-g4nw4d

**4. Steps to reproduce**

1. Clone this repository https://github.com/olivierlarose/cursor-hover-mask/tree/main
2. Install with included dependencies
3. Animation works fine
4. Update to latest Framer Motion version
5. Start project
6. Animation is super laggy

**5. Expected behavior**

Expect the animation to be smooth, as in v10

**6. Video or screenshots**

Bad behaviour v10
https://github.com/framer/motion/assets/4519142/991827e3-d109-47ee-90c5-53e8a211ddcb

Bad behaviour v11
https://github.com/framer/motion/assets/4519142/36038fb3-126c-49e9-8c03-28e9f46d3ee0

**Comment by erengy** [comment] 2024-03-21 12:28
I'm having the same issue after updating from 11.0.8 to 11.0.18.

Looks like it was introduced in 11.0.11, since reverting to 11.0.10 works for me. Might be related to #2448 or #2528.

**Comment by rnnyrk** [comment] 2024-03-21 13:05
Can confirm I get the expected behaviour with 11.0.10 indeed @erengy

**Comment by rnnyrk** [comment] 2024-03-21 15:45
@mattgperry Sorry wasn't aware it was private. Changed it and should be public now

**Comment by mattgperry** [comment] 2024-03-21 15:50
Thanks!

**Comment by mattgperry** [comment] 2024-03-21 15:55
Ah yeah I'll have to take a look. Preferably what you'd do here is something with motion values and avoid rerendering. But although not the most performant way to do this, it should still work visually. It's happening because we now defer resolving keyframes until the next animation frame. I'll have to have a play and figure out what to do in these situations, maybe an opt-out or something.

**Comment by sozuki** [comment] 2024-03-25 06:36
The same issue:
[Demo with a new version](https://codesandbox.io/p/devbox/framer-motion-10-14-0-forked-nmqrhh?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu6k2ugh00072866xd1009og%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu6k2ugh00022866pa3sbtof%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu6k2ugh00042866433kibvn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu6k2ugh00062866bt5yyhzt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu6k2ugh00022866pa3sbtof%2522%253A%257B%2522id%2522%253A%2522clu6k2ugh00022866pa3sbtof%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu6k2ugh00062866bt5yyhzt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu6k2ugh00052866lvsucuey%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu6k2ugh00062866bt5yyhzt%2522%252C%2522activeTabId%2522%253A%2522clu6k2ugh00052866lvsucuey%2522%257D%252C%2522clu6k2ugh00042866433kibvn%2522%253A%257B%2522id%2522%253A%2522clu6k2ugh00042866433kibvn%2522%252C%2522activeTabId%2522%253A%2522clu6k2ugh00032866e9gfp8td%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu6k2ugh00032866e9gfp8td%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clu6k9d3y00du2866l31fc8zy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu6k9d4f00hgd9ge7nqhe7rq%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) is laggy
[Demo with 10.14 version](https://codesandbox.io/p/devbox/framer-motion-10-14-0-wzrkxm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu6k2ugh00072866xd1009og%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu6k2ugh00022866pa3sbtof%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu6k2ugh00042866433kibvn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu6k2ugh00062866bt5yyhzt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu6k2ugh00022866pa3sbtof%2522%253A%257B%2522id%2522%253A%2522clu6k2ugh00022866pa3sbtof%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu6k2ugh00062866bt5yyhzt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu6k2ugh00052866lvsucuey%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu6k2ugh00062866bt5yyhzt%2522%252C%2522activeTabId%2522%253A%2522clu6k2ugh00052866lvsucuey%2522%257D%252C%2522clu6k2ugh00042866433kibvn%2522%253A%257B%2522id%2522%253A%2522clu6k2ugh00042866433kibvn%2522%252C%2522activeTabId%2522%253A%2522clu6k2ugh00032866e9gfp8td%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu6k2ugh00032866e9gfp8td%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clu6k9d3y00du2866l31fc8zy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu6k9d4f00hgd9ge7nqhe7rq%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) is more stable
Also, if I just change the transition duration to 0, it updates everything without delays. Hope it helps

**Comment by quentinlagache** [comment] 2024-05-10 14:05
> Ah yeah I'll have to take a look. Preferably what you'd do here is something with motion values and avoid rerendering. But although not the most performant way to do this, it should still work visually. It's happening because we now defer resolving keyframes until the next animation frame. I'll have to have a play and figure out what to do in these situations, maybe an opt-out or something.

Any update on this topic @mattgperry ?

**Comment by mattgperry** [comment] 2024-05-15 11:37
I'm going to have a look at this now. It **might** be that the per-frame render simply isn't fixed, I'll have to look into if that's possible (the perf increase of this within Framer > that pattern). But this approach https://codesandbox.io/p/sandbox/framer-motion-spring-transition-e6c8dm?file=%2Fsrc%2Fuse-follow-pointer.ts%3A23%2C1&from-embed= should work better than it currently is too. Annoyingly this one is very hard to write a good test around as it can be anywhere between very obvious and very subtle.

**Comment by mattgperry** [comment] 2024-05-15 12:28
Unhelpfully:
- A recreation of the bug locally shows "better" (but not perfect) spring following
- Turning on a recording via the Performance tab makes it start working perfectly (locally but not on the sandbox)

**Comment by mattgperry** [comment] 2024-05-15 12:30
https://github.com/framer/motion/assets/7850794/596140bc-7097-439d-9f9a-69c3f6fcc280

**Comment by mattgperry** [comment] 2024-05-15 13:02
Oops. I had forced it back into sync mode, hence the better performance. Really strange about the performance recording though.

**Comment by mattgperry** [comment] 2024-05-16 12:56
FYI I have a fix. It doesn't fix the use case of re-rendering once per animation frame, but as I originally said I am hesitant to address this. However it does make `useSpring` much more resilient to when and how often it is called - leading to smoother spring animations. I'll update our example to show the correct pattern once published.

**Comment by mattgperry** [comment] 2024-05-16 13:48
Here's a version of your demo that uses `useSpring` to achieve a similar effect without re-rendering https://codesandbox.io/p/devbox/framer-motion-animation-lag-forked-wzp99c?file=%2Fsrc%2Fapp%2Fpage.js%3A15%2C28&workspaceId=a5b3421f-f215-4447-bd06-fd2db6cf83b4

**Closed** 2024-05-16 19:22 UTC
Labels: bug

**Comment by erengy** [comment] 2024-05-17 01:50
Thanks for the demo, @mattgperry. I can confirm that after updating to 11.2.4, tracking the cursor with motion values and positioning the mask with `useSpring` and `useTransform` works for me.
