### ISSUE TITLE
[BUG] AnimatePresence initial={false} is applied to all components below it in the render tree

### ISSUE THREAD

**Issue by dminkovsky** [framer/motion#724] opened 2020-08-23 04:54 UTC
**2. Describe the bug**

`<AnimatePresence initial={false}>` suppresses initial state for all motion components below it in the render tree, not just descendants with `exit` props. 

The result is that at any arbitrary depth below an `<AnimatePresence initial={false}>`, `initial` motion state is suppressed.

In my case, I was trying to use `initial` to set [initial state for animation controls](https://github.com/framer/motion/issues/437). After struggling for a long time to figure out why this initial state was not rendering, I finally figured out it was due to an `AnimatePresence` way, way higher up in the render tree, responsible for animating route transitions. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Please see https://codesandbox.io/s/animatepresence-initialfalse-037n8?file=/src/App.js:1159-1180. Notice how the variant on line 18 is not applied on first render.

**4. Steps to reproduce**

Please see CodeSandbox above.

**5. Expected behavior**

`initial={false}` from `AnimatePresence` should apply only up to the depth of the first descendants that are encountered with an exit prop. After that, initial effects should still work, at least for motion components controlled by Animation Controls, where settings initial state seems to be required for animating later anyway. Or maybe something like how 

> These changes in variant will flow down until a child component defines its own animate property.

(which, however, [does not work with controls](https://github.com/framer/motion/issues/288), so maybe that's an issue here too).

**Comment by dminkovsky** [comment] 2020-08-23 16:50
So I tried nesting the counter-acting AnimatePresence. I added it in the same component as the one it's counter-acting, to keep the two together in the code. (Tthe use-case is router transitions.) It looked like this:

<img width="638" alt="Screen Shot 2020-08-23 at 12 42 25 PM" src="https://user-images.githubusercontent.com/218725/90983734-449b8f80-e53e-11ea-89bf-c942b2e70af5.png">

The result works but I get this warning upon route transition.

<img width="636" alt="Screen Shot 2020-08-23 at 12 44 05 PM" src="https://user-images.githubusercontent.com/218725/90983757-567d3280-e53e-11ea-8c0c-8d3ed4b83fb1.png"> 

So I added a keyed fragment to avoid this warning:

<img width="591" alt="Screen Shot 2020-08-23 at 12 49 25 PM" src="https://user-images.githubusercontent.com/218725/90983845-208c7e00-e53f-11ea-8083-e329cdad5132.png">

which really does feel like abusing the AnimatePresence API. Seems to be working, but feels wrong to me:

**Comment by InventingWithMonster** [comment] 2020-08-23 16:54
Could you not just  add the key to the MenuBar component?

**Comment by dminkovsky** [comment] 2020-08-23 17:02
Oh yes, you're right, that's better.

**Comment by InventingWithMonster** [comment] 2020-08-25 13:38
Treating this as a `wontfix` for now. Adding an `AnimatePresence` barrier here is totally supported. The problem is, any `exit` animations within the tree are counted towards the removal of it. This works whether there are multiple top-level `motion` components within a tree, or the top-level components don't have an `exit` prop but other children do.

As a result it is intentional that `initial` would also apply equally to the same children, bearing in mind that this component is used for controlling *presence* animations, not just *exit* animations.

**Closed by InventingWithMonster** 2020-08-25 13:38 UTC
Labels: bug

**Comment by dminkovsky** [comment] 2020-08-25 13:56
Makes sense. Thank you @InventingWithMonster, @blasterpistol
