### ISSUE TITLE
[BUG] Drag element and layout prop

### ISSUE THREAD

**Issue by KirdesMF** [framer/motion#976] opened 2021-02-15 16:32 UTC
**Describe the bug**

There is one element with p tag in it. if I set this element to be draggable,  all works fine.
but in this element, there is an other p tag wrapped in `AnimatePresence` because it shows only onTap.
so, to have a smooth layout animation, it's needed to add the layout prop, but since we add this layout prop those p tag wont come with the draggable element.

I've also tried with layoutId.

maybe I'm missing something.

**IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/pensive-meadow-81qdn?file=/src/App.js

**Steps to reproduce**

1. Go to the sandbox linked above.
2. Drag an element
3. Children wont follow the draggable div

**Expected behavior**
Children should follow the draggable element even with the layout prop

**Video or screenshots**

Before drag:

![image](https://user-images.githubusercontent.com/54989552/107970397-591e8900-6fb1-11eb-8d9c-6343cec1ecea.png)

During drag:

![image](https://user-images.githubusercontent.com/54989552/107970475-718ea380-6fb1-11eb-8911-d709d5ba632d.png)

**7. Environment details**

Win 10. React 17.01 . framer-motion 3.3.0

**Comment by mattgperry** [comment] 2021-03-04 09:26
Duplicate of https://github.com/framer/motion/issues/636

**Closed by mattgperry** 2021-03-04 09:26 UTC
Labels: bug, layout projection
