### ISSUE TITLE
[BUG] Error when animating translateY (introduced in 10.12.16)

### ISSUE THREAD

**Issue by dd-jonas** [framer/motion#2179] opened 2023-06-07 07:24 UTC
**1. Read the [FAQs](#faqs) 👇**

**2. Describe the bug**

I'm encountering an uncaught error when animating translationY from 0px to 100%.

There's seems to be a change introduced in 10.12.16 that is related to animating `translateX` and `translateY`. These properties have been added to the `positionalKeys` map, but are missing from the `positionalValues` map, resulting in a call to an undefined function as `positionalValues['translateY']` does not exist (`render/dom/utils/unit-conversion.ts`).

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[Link](https://stackblitz.com/edit/stackblitz-starters-n4wngs?file=src%2FApp.tsx)

**4. Steps to reproduce**

1. Go to the sandbox above
1. Click on the toggle button
1. See error

**5. Expected behavior**

No error. (The animation in the sandbox might not make sense, but in my application I'm using it to slide out a navigation menu.)

**6. Video or screenshots**

*The error message should be enough*

**7. Environment details**

Not relevant

**Comment by dd-jonas** [comment] 2023-07-03 09:30
Any updates on this?

**Comment by mirka** [comment] 2023-07-20 18:23
I think we can close — this looks like a dupe of #2169, which was fixed and shipped in 10.12.19 🎉

**Closed** 2023-07-20 21:15 UTC
Labels: bug
