### ISSUE TITLE
[FEATURE] More control over nested 'magic motion' layout transitions

### ISSUE THREAD

**Issue by rijk** [framer/motion#864] opened 2020-11-23 10:58 UTC
Consider the following example:

```jsx
<Icon layoutId="step" onClick={() => setOpen( true )} />
{open && <Modal layoutId="step" />}
```

This gives us a nice iOS-style opening animation: https://codesandbox.io/s/happy-shadow-kizdd

**Problem: nested `layout`**
When we want to add magic motion _inside_ of the `Modal`, for instance to open/close the sidebar panel, it gets tricky. If we do something like this:

```jsx
const Modal = () => (
  <motion.div layoutId="step">
    <motion.div layout className="content" />
    {sidebar && <aside />}
  </motion.div>
)
```

…by nature of how 'magic motion' works, the `layout` on `.content` (that's meant for animating the open/close of the sidebar) will _invert_ the modal zoom transitions. This will make the content seem to be fixed in the same place, instead of zooming in/out with the modal. This is obviously unwanted, but there's no way to prevent this.

**Describe alternatives you've considered**
The only way to work around this is to micromanage the animations, for instance by disabling the layout transitions while the modal animation is running: https://codesandbox.io/s/confident-dream-g0l74?file=/src/Board.tsx. However, this is clunky and imperfect, as you can see e.g. when closing the modal.

**Describe the solution you'd like**
Ideally, framer-motion would handle these cases 'magically' as well. @mattgperry [talked about an idea](https://github.com/framer/motion/issues/636#issuecomment-659974795) that might solve this as well (not sure):

> At some point soonish I want to look into resolving these bounding boxes relatively to parents so I imagine this will fix that.

If it's not possible to do this automagically, we at least need more control over the layout animations to be able to specify different transitions and disable/enable layout transitions based on the context.

**Comment by mattgperry** [comment] 2023-01-02 14:35
I believe dupe of https://github.com/framer/motion/issues/1027 ?

**Closed by mattgperry** 2023-01-02 14:35 UTC
Labels: feature
