### ISSUE TITLE
Layout Scaling Stretchy Border

### ISSUE THREAD

**Issue by mohux** [framer/motion#1249] opened 2021-09-07 14:16 UTC
When using AnimateSharedLayout with "layout" attribute, 
the borders stretch and sometimes get blurry

when I debugged its because of scaling and transform3d changes
what could be the solution to achieve such animation that a button scales to full width while going to top position?

should we use layoutId while having 2 lists one for selected and one for unselected, or there is a solution by using layout?

https://user-images.githubusercontent.com/57658626/132360004-cc041f05-b7c8-4612-aabd-372c44afccce.mov

**Comment by mattgperry** [comment] 2021-09-07 14:23
I would create the border with nested motion.divs with layout. It sounds counter-intuitive but ultimately layout animations are performant because they use transforms. Scale distorts content, which can be corrected for some props. But we don't include border because border triggers layout. You lose the perf benefits (and actually get substandard results because you cant render borders less than 1px).

**Comment by mohux** [comment] 2021-09-07 14:29
I made some kind of resembling issue here 
https://codesandbox.io/s/framer-motion-reorder-animation-forked-5kj6z?file=/src/Example.tsx

**Comment by mohux** [comment] 2021-09-07 14:30
I tried to create the border using motion.div that has a layout inside it yet still not working

**Comment by mohux** [comment] 2021-09-07 14:32
> I would create the border with nested motion.divs with layout. It sounds counter-intuitive but ultimately layout animations are performant because they use transforms. Scale distorts content, which can be corrected for some props. But we don't include border because border triggers layout. You lose the perf benefits (and actually get substandard results because you cant render borders less than 1px).

Thanks for replaying @mattgperry, the issue is even happening with background colors showing some kind of blurs if you see the example and even try to hide the borders

**Comment by mohux** [comment] 2021-09-07 14:39
Though I tried to create the border using shadows (rings in tailwind) still the exact same results show

**Comment by mattgperry** [comment] 2021-09-07 14:49
If you pass `boxShadow` as a `style` it will be automatically scale
corrected but not if you pass it via className. It will still
squish/stretch a little bit though as your aspect ratios are very different
and boxShadow doesn't have per-axis blur control

**Comment by mattgperry** [comment] 2021-09-07 14:49
I'd be interested at seeing the source code of your attempt with nested
motion.divs though as that should work

**Comment by mohammadou1** [comment] 2021-09-07 17:03
I will try out adding it as style not as class hoping it will work
Will let you know and will create another real reproduction in case it doesnt

**Comment by mattgperry** [comment] 2021-11-23 15:52
@dmahajan980 That looks great!

Closing this for now as we don't support border correction, the nested approach should work as in this sandbox ^

**Closed by mattgperry** 2021-11-23 15:52 UTC
Labels: bug
