### ISSUE TITLE
[BUG] Crossfade Spring transition with duration flickers back to initial state at end

### ISSUE THREAD

**Issue by rijk** [framer/motion#1080] opened 2021-04-01 09:55 UTC
This cropped up in #1023 , but appears to be a separate issue. Here's a recording:

https://user-images.githubusercontent.com/159500/113273257-c3c72200-92dc-11eb-8fa7-fde2309a87a0.mov

**CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-330-issue-with-layout-animations-forked-xjz75?file=/src/App.js

After some trial and error, I see that it strongly depends on the type of transition:

**Works:**

```typescript
const transition = {
  type: "spring",
  stiffness: 400,
  damping: 50
};
```

**Also works:**

```typescript
const transition = {
  duration: 1
};
```

**Doesn't work:**

```typescript
const transition = {
  type: "spring",
  duration: 1
};
```

This is not a new issue by the way, I found it happens in framer-motion@3.3.0 as well, so it's probably not related to layout projection but to transition calculations.

**Comment by mattgperry** [comment] 2021-04-01 09:57
It is related to the crossfader by the looks of it, I'll take a look next week tho

**Comment by rijk** [comment] 2021-04-01 10:04
Perhaps related to #1024; when I change that to `<AnimateSharedLayout type="switch">` (from crossfade) it [seems to solve the issue](https://codesandbox.io/s/framer-motion-340-state-update-triggers-layout-animation-forked-ofd8f?file=/src/Board.tsx).

**Comment by mattgperry** [comment] 2021-04-01 12:07
Hmmm based on the transitions you've posted I wonder if the problem is overshooting the crossfade (which works as `0` for fully the previous values or `1` for fully the incoming values)

I'll take a look

**Comment by mattgperry** [comment] 2021-04-01 12:35
I think I've got a fix for this - as an aside you don't need to animate the border radius, just to add it to `style`, it should be crossfaded between the two components still. As it currently is, it's getting crossfaded from `20` from the grey box to whatever the latest value of the blue box's borderRadius animation is

**Closed** 2021-04-01 12:36 UTC
Labels: bug, layout projection

**Comment by rijk** [comment] 2021-04-01 13:19
Cool, works like a charm from the looks of things. 

> as an aside you don't need to animate the border radius

Gotcha, updated [the Sandbox](https://codesandbox.io/s/framer-motion-330-issue-with-layout-animations-forked-nietf?file=/src/App.js). Seems I don't even need a `style={{ borderRadius: 0 }}` on the open state, because that's inferred as the default value, correct?

Regarding adding border radius to `style`, has this been changed at some point? In your 2.x examples [you were using `initial`](https://codesandbox.io/s/1cpd0) for this. Any reason why this has to be added to `style` as opposed to the CSS? I thought the idea of `layout` was that it would just interpret the before and after, and calculate the in-between states (like in your flexbox toggle example). Is it because border radius is too complex for this, with the scale correction and all? Are there more CSS properties to which this applies?

**Comment by rijk** [comment] 2021-04-01 16:12
Another question: if I don't explicitly animate borderRadius (let `layout` take care of it), the `transitionEnd` no longer works:

```typescript
animate={{
  borderRadius: 0,
  transitionEnd: {
    overflow: "visible",
    pointerEvents: "auto"
  }
}}
```

Sandbox: https://codesandbox.io/s/framer-motion-330-issue-with-layout-animations-forked-fqg2f?file=/src/App.js (comment/uncomment line 54 to see the difference).

Use case: I need the element to allow overflow for app specific reasons, but during the transition I need `overflow: hidden` because otherwise the border radius will have no visible effect.

Is there a way to do this with `layout`?

**Comment by mattgperry** [comment] 2021-04-01 17:44
Hmm probably not at the moment, good point. For the border radius it’s just more predictable to always get it from the same place, the internal motion values, rather than measuring from the Dom
