### ISSUE TITLE
[BUG] layout prop doesn't animate list after item is removed

### ISSUE THREAD

**Issue by bakoushin** [framer/motion#756] opened 2020-09-09 07:22 UTC
In the example [Notifications](https://codesandbox.io/s/framer-motion-notifications-5cvo9?file=/src/Example.tsx:498-516) provided in the docs, the position of notifications stack is automatically animated using `positionTransition` prop: either when a new notification is added to the stack, or when an existing notification is removed.

In Framer Motion 2 `positionTransition` prop is [deprecated](https://www.framer.com/api/motion/guide-upgrade-to-framer-motion-2/#layout-animations) in favor of [`layout`](https://www.framer.com/api/motion/component/#layout-animation) prop.

However, if we simply change `positionTransition` to `layout` prop in the official example, it still animates adding a notification but **doesn't animate the stack when a notification is removed**. [CodeSandbox reproduction](https://codesandbox.io/s/framer-motion-notifications-forked-v70yv?file=/src/Example.tsx:482-488)

**Steps to reproduce**

1. Open CodeSandbox example: 
  * [Framer Motion 1 with `positionTransition`](https://codesandbox.io/s/framer-motion-notifications-5cvo9?file=/src/Example.tsx:498-516) 
  * [Framer Motion 2 with `layout`](https://codesandbox.io/s/framer-motion-notifications-forked-v70yv?file=/src/Example.tsx:482-488)
2. Add several notifications. Notice the position animation.
3. Remove notification **in the middle of the stack**. Notice that position animation for the rest of the stack doesn't happen in Framer Motion 2 example using `layout` prop. 

**Expected behavior**

The position of the notifications stack is automatically animated when an existing notification is removed.

**Comment by InventingWithMonster** [comment] 2020-09-09 08:16
Ah yeah this seems to be a regression with the latest release. Using `2.6.5` will work while I look into this. Thanks for the report!

**Comment by InventingWithMonster** [comment] 2020-09-09 09:54
This has been fixed in `2.6.9`

**Closed by InventingWithMonster** 2020-09-09 09:54 UTC
Labels: bug

**Comment by pablen** [comment] 2021-08-20 19:35
Could the Notifications example and/or docs be updated to reflect this change?

The example is exactly what I needed but it doesn't work as expected with current version (4.1.17).
