### ISSUE TITLE
[BUG] Wierd scaling when using drag and initial animation variants with a scaleY set to 0

### ISSUE THREAD

**Issue by Sandstedt** [framer/motion#677] opened 2020-07-29 15:22 UTC
**2. Describe the bug**

In version 2.3.0 (worked in 2.0.0-beta.33), there is a null check somewhere in the source-code that skews up the object at start. This only occurs if it has prop drag, and an initial animation variant where either scaleX or scaleY is set to 0 (and, sorry, also some other factor, can't reproduce outside my project, of course).

The objects gets `opacity: 1; transform: translate3d(0px, 0px, 0px) scale(1, 12.5732); user-select: none; transform-origin: 50% 47.4619% 0px;` at start. When I start to drag it around, it fixes itself: `opacity: 1; transform: translate3d(21.1105px, 46.3471px, 0px) scale(1); user-select: none; transform-origin: 50% 100% 0px;`.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

Here's a working example without the bug. As I said above. This bug only happens in my project :(. But will dig into this bug a bit more and see if I can reproduce it in the example below.

https://codesandbox.io/s/hopeful-golick-926kz?file=/src/App.js

**4. Steps to reproduce**

1. Open the page
2. The modal is now scaled an enormous amount.
3. Drag around the modal, and the scaling is now restored.

**5. Expected behavior**

Should not scale up wierdly :). But can be solved to setting scale to anything other than 0, that is a falsy value. Ex 0.0001.

**6. Video or screenshots**

Sorry, it's still confidential. Can upload a failing version in maybe 2 weeks.

**7. Environment details**

Firefox 79 on Mac using Framer Motion 2.3.0

**Comment by InventingWithMonster** [comment] 2020-07-31 10:16
It's quite weird how it only happens in your project but its difficult for me to look into this without a reproduction.

What I would recommend is to inspect each element and ensure that the CSS applied is the same in both the sandbox and your repo. You could then perhaps apply that CSS in the sandbox.

I'm going to close this for now as I do need a reproduction to look into this efficiently, but if you are able to get one then please feel free to reopen and I'll take a look.

**Closed by InventingWithMonster** 2020-07-31 10:16 UTC
Labels: bug

**Comment by francescoCoriolano** [comment] 2023-11-13 11:35
I'm also facing the same issue here is how it looks like 

https://github.com/framer/motion/assets/109538519/02a63f3e-d1a2-4276-a486-6c87e736d59e
