### ISSUE TITLE
[BUG] Promises returned by controls never fulfil

### ISSUE THREAD

**Issue by danielo515** [framer/motion#1090] opened 2021-04-08 08:24 UTC
**2. Describe the bug**

Promises returned by the control methods of the controls returned by useAnimation never fulfils.

```js
  const controls = useAnimation()

  useEffect(() => {
    if (isOpen) controls.start('open').then(console.log.bind(null, 'I am open'))
  })

      <>
        <motion.div
          className={`${styles.modalBackdrop}`}
          variants={{ open: visible, closed: nonVisible }}
          initial={ClosedVariant}
          transition={{ duration }}
          animate={controls}
          ref={ref}
          onMouseDown={handleOverlayClick}
        >
          <motion.div
            variants={variants}
            initial={ClosedVariant}
            animate={controls}
            className={classes}
            transition={{ duration }}
          >
            {children}
          </motion.div>
        </motion.div>
      </>
```

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

I tried to reproduce it by all means possible, but I am not able. I fixed it on my original codebase by not passing the controls reference to the nested component you can see on the snippet above. But my reproduction example also has that "defect" and it still works. I will keep trying to reproduce it on the following sandbox:

https://codesandbox.io/s/framer-controls-promises-not-fulfilling-luqyq?file=/src/Example.jsx

**4. Steps to reproduce**

1. Go to the sandbox
2. Use the ESC key to toggle the content
3. Keep the console open to see if the console.log calls inside the then methods are called

**5. Expected behavior**

I expect the promise to fulfil, even if its because a timeout,

**6. Video or screenshots**

Nope

**7. Environment details**

```
  System:
    OS: macOS 11.1
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
  npmPackages:
    react: ^16.14.4
    react-dom: ^16.14.4
    framer-motion: 4.1.3
```

If applicable, let us know which OS, browser, browser version etc you're using.

**Comment by jedimonkey** [comment] 2021-11-08 02:51
I've hit this bug as well and dug into the code a little. As soon as there are multiple elements sharing a motionValue, the promise never fulfils. With the promise that gets created (https://github.com/framer/motion/blob/a838606b66f74bf4ea730f3cbc0d1fe2b2e6a780/src/animation/animation-controls.ts#L50) the last element only ever fulfills, the other promises sit there pending. I haven't been able to dig into the code further to understand what's happening with the other promises, but I presume due to it manipulating a MotionValue it's updating multiple times.

**Comment by mattgperry** [comment] 2022-06-02 12:22
Closing this out as I can't reproduce. The open animation is never run (based on logs) so shouldn't expect the promise to resolve, but the close animation does run and resolve. If someone can make a clearer sandbox please feel free to reopen and I'll take a look

**Closed by mattgperry** 2022-06-02 12:22 UTC
Labels: bug
