### ISSUE TITLE
[BUG] Lingering `requestAnimationFrame` when removing animated component

### ISSUE THREAD

**Issue by DerNamenlose** [framer/motion#1048] opened 2021-03-20 23:38 UTC
When removing an animated component with an infinite loop, there is a lingering `requestAnimationFrame` in the background, that keeps on using the CPU. 

**CodeSandbox**
https://mo41z.csb.app/

**4. Steps to reproduce**

1. Conditionally render a component with an animation with `loop: Infinity`.
2. Remove that component from the DOM by setting the condition to false.
3. Create a Performance Profile in DevTools -> there is a `requestAnimationFrame` running every 16 ms (for my 60 Hz monitor anyway), even though there is no longer any animated component in the DOM.
4. (Unsure) The `requestAnimationFrame`-calls seem to add up, causing 100% CPU in a long running process (Electron App in my case). However, I'm not 100% positive on how to actually reproduce this reliably.

**5. Expected behavior**

When the animated component is removed, the calls to `requestAnimationFrame` should stop, relinquishing any control of the CPU.

**7. Environment details**

Electron 12.0.1 (Chromium 89.0.4389.82) on Kubuntu 20.10.

**Comment by fedekau** [comment] 2021-11-24 17:46
@DerNamenlose did you find out something that helped you resolve the problem?

We have something very similar, just by doing this we are able to reproduce it 🤯 

```
<AnimatePresence>
   <div>Hi</div>
</AnimatePresence>
```

**Comment by fedekau** [comment] 2021-11-24 17:50
@mattgperry I am pinging you since I saw you active on a thread about `requestAnimationFrame` too. Does this have an explanation? Our Framer version is `4.1.17`. Let me know if you need more details

**Comment by DerNamenlose** [comment] 2021-11-29 09:51
@fedekau Sorry, I replaced the animation with a CSS animation due to a code overhaul anyway.

**Comment by fedekau** [comment] 2021-11-29 10:38
Thanks @DerNamenlose!

We needed an animation to run infinitely as long as the component was mounted so we ended up forcing the animation by changing the key `onAnimationCompleted`. Basically infinity loop, but manually. 

```jsx
const [key, setKey] = useState(0);

return <motion.div key={key} onAnimationCompleted={() => setKey(key+1)} ...>...</motion.div


```

**Comment by fatso83** [comment] 2022-03-04 01:17
Any idea on how to fix this in code? I made a full reproduction case after profiling this for a while.
https://github.com/fatso83/issue-reproductions/tree/master/framer-motion-cpu-issue

For us, the quickfix was to just set `repeat` to some non-infinite number that would cover most probable max-times of the animation, but that is a hack. What seems to be missing is calling the animation's `.stop()` on unmount using `useEffect()` or similar, but stepping through the code and manually reading through the checked out repo did not really get me all that closer to where this was supposed to happen, so I have not been able to come up with a PR.

**Comment by fatso83** [comment] 2022-03-04 01:36
Seems this is related to #886, possibly being a duplicate, seeing that they also mention needing to set a non-infinite number to stop the animation.

**Comment by fatso83** [comment] 2022-03-04 05:00
I have stepped around for a few hours, messing with [my repro case](https://github.com/fatso83/issue-reproductions/tree/master/framer-motion-cpu-issue) modifying stuff directly in node_modules while simultaneously checking the untranspiled original source code. This asserted that my theory was sound: manually calling the `stop()` functions on the individual Popmotion animations got rid of the cpu usage. Specifically, I modified the internal `start()` method inside of `getAnimation()` in `animations/utils/transitions.js` to create a wrapper around the original return value, so that I could create my own stop that would push references to the stop method in `window.fmStops`. Then later on, doing `window.fmStops.map(stop => stop())` cancelled all the processing.

The Framer Motion library does take try to keep the ability `stop` the animations. For instance, 
as Popmotion's `animate()` will return an object with some methods to control the animation, the "bridge" interface of `getAnimation()` and `startAnimation()` ensures to pass this on, so that when calling them you get objects back that you can call `.stop()` on. But at some point further up this gets a bit lost, approximately where we start introducing `Promise`s and the animations get wrapped by MotionValue and VisualElement and what not. So nothing calls back to the animations to tell them to lay it off. 

`useVisualElement()` does call `visualElement.notifyUnmount()`, but there are no listeners to this that would trigger the underlying motion value to stop.

The final puzzle I was not able to pin down was how/where/who to call the `MotionValue#stopAnimation()`. I see from `animateTarget` (called indirectly by useVisualElement) that you can get at the motion value using `visualElement.getValue("opacity")` (or whatever the current target is), but it is not immediately obvious how to get to it from further up the chain. So I guess getting `visualElement` itself to listen for `unmount` events could be a way, since it has all the data required.

**Comment by fatso83** [comment] 2022-03-04 05:23
OK, found a fix for this. PR coming up.

**Comment by fatso83** [comment] 2022-03-04 12:53
Here is the patches for 2.9.5 (which we were originally using when I found this issue, which was still present in the latest release) which you can apply using [`patch-package`](https://www.npmjs.com/package/patch-package) without waiting for a later release. For other versions, you just need to open `node_modules/framer-motion/dist/framer-motion.es.js`, scroll down to the section for `node_modules/framer-motion/dist/framer-motion.es.js`  and patch the `unmount` function of VisualElement (called AnimationControls earler). 

```
diff--git a/frontend/patches/framer-motion+2.9.5.patch b/frontend/patches/framer-motion+2.9.5.patch
newfile mode 100644
index0000000000..f61021b654
-- /dev/null
++ b/frontend/patches/framer-motion+2.9.5.patch
@@-0,0 +1,23 @@
# generated by patch-package 6.4.8 on 2022-03-04 13:44:29
#
# command:
#   npx patch-package framer-motion
#
# declared package:
#   framer-motion: 2.9.5
#
diff --git a/node_modules/framer-motion/dist/framer-motion.es.js b/node_modules/framer-motion/dist/framer-motion.es.js
index 4dfe8f9..f84692f 100644
--- a/node_modules/framer-motion/dist/framer-motion.es.js
+++ b/node_modules/framer-motion/dist/framer-motion.es.js
@@ -5073,6 +5073,10 @@ var AnimationControls = /** @class */ (function () {
      * @internal
      */
     AnimationControls.prototype.unmount = function () {
+        this.forEachValue(function (value, key) {
+          value.stop()
+          return _this.removeValue(key)
+        })
         this.hasMounted = false;
         this.stop();
     };
```

**Closed** 2023-01-02 09:56 UTC
Labels: bug
