### ISSUE TITLE
[FEATURE] No link to code example

### ISSUE THREAD

**Issue by ovidubya** [framer/motion#1232] opened 2021-08-03 17:46 UTC
**Describe the solution you'd like**
Would it be possible to include a link to a code sandbox or codepen to the following example shown in https://framer.com/motion 

## Example 
<img width="1454" alt="Screen Shot 2021-08-03 at 12 45 57 PM" src="https://user-images.githubusercontent.com/22357156/128061898-ce3d4afc-1c2a-48d5-b7ca-385bfdd4fd92.png">

**Comment by o-alexandrov** [comment] 2021-11-30 11:06
duplicate of https://github.com/framer/motion/issues/905

**Comment by mattgperry** [comment] 2024-01-03 09:48
Closing as a `wontfix` as I'm unlikely to find the time for this one.

**Closed by mattgperry** 2024-01-03 09:48 UTC
Labels: feature
