### ISSUE TITLE
[FEATURE] LayoutBoundary component

### ISSUE THREAD

**Issue by rijk** [framer/motion#1027] opened 2021-03-11 09:17 UTC
The `layout` property is positioned as magic dust that you sprinkle anywhere stuff changes in your app to make it animate. There's little control and configuration, as it's aimed to _just work_. And in smaller trees it does, wonderfully.

**The problem:** in larger apps there are often several 'sublayouts' (see below for an example), and that is where this starts to break down. Currently, there is only one level of `layout`, affecting the whole tree. As a result, you can get unwanted scale correction in sublayout components because of their `layout` property. In the example below for instance, when opening the Modal, the content and sidebar won't 'zoom in' with the modal, as they invert that animation (so they will appear in the end position while the zoom is happening). 

<details>
<summary>A real-world example of sublayouts</summary>

Here's a wireframe of my app with arrows to indicate some of the animations:

![Layout](https://user-images.githubusercontent.com/159500/110760053-955ea580-824e-11eb-90b5-1943d75ae7e1.png)

</details>

Currently, the only way to work around this is installing an intricate system of timeouts, that wait to activate the sublayout's `layout` property until after the modal has opened;

```tsx
<motion.div className="sidebar" layout={!modalOpening}>
```

**Proposed solution:** a `<LayoutBoundary>` component could offer a nice, declarative and opt-in way to give the user more control by defining the sublayouts in their tree. It's kind of a reverse `<AnimateSharedLayout>`.

What it should do roughly is to 'swallow' layout changes coming from the parent. So it creates an isolated context for layout updates.

<details>
<summary>How this would look in the above example</summary>

The colored edges define the layout boundaries:

![Layout boundaries](https://user-images.githubusercontent.com/159500/110763977-c640d980-8252-11eb-9f9f-9cc5d0cce192.png)

</details>

**Comment by rijk** [comment] 2021-03-17 20:37
Here's another example:

https://user-images.githubusercontent.com/159500/111534657-85702580-8768-11eb-8968-0eee04d4ad3e.mov

**Desired behaviour:**

- Projects (white rows) animate down
- Squares animate sideways within the project

**Observed behaviour:**

- Squares break out of their parent while animating

I think this could also potentially be solved with a `<LayoutBoundary>` inside each project.

**Comment by gurkerl83** [comment] 2021-04-23 11:53
It would be nice to have more control of layout animations. My use case is a navigation component with views; each can have a list with different scroll positions; the problem is scroll restoration. It seems shared layout and scrollTo in a layout/effect to correct the scroll position are not playing well with each other.

**Comment by mattgperry** [comment] 2024-01-02 14:36
Closing as `wontfix` to set expectations.

It's still possible this could be implemented, but it's unlikely to happen unless we need the functionality inside Framer.

**Closed by mattgperry** 2024-01-02 14:36 UTC
Labels: feature
