### ISSUE TITLE
Unmount animations for Suspense Fallback component?

### ISSUE THREAD

**Issue by samselikoff** [framer/motion#1193] opened 2021-06-22 09:50 UTC
It looks like Suspense currently doesn't support unmount animations for its Fallback component. There are a few related discussions/RFCs in the React repo [like this one](https://github.com/reactjs/rfcs/pull/154).

Curious if there are currently any known/good workarounds for this? I've been toying with something like [this example from a SO answer](https://stackoverflow.com/a/61598220/1406664) where I force a data-loading component to continue suspending until after a <Fallback /> completes a fadeOut animation using a MotionValue and `animate()` function, but haven't landed on anything decent yet.

Just wondering if anyone has any good alternatives for the time being!

**Comment by lunelson** [comment] 2021-09-15 15:56
I'd also be really interested in any solutions to this. I'm trying to figure out how to do page transitions, but wait for the sections of the page which are code-split.

**Comment by lunelson** [comment] 2022-01-18 11:27
@samselikoff @mattgperry on a related note:

Could it be possible to coordinate `Suspense` with `AnimatePresence` in such a way as to avoid rendering the `fallback`—or in other words, wait for the suspended component to resolve? I'm thinking of a page-transition scenario where `AnimatePresence` is wrapped around a `Page` component that contains async items (think `loadable-components,` or `next/dynamic`). 

Naïve example: here I'd like to get `AnimatePresence` to wait until `Suspense` resolves the `Page`, not transition from `Page` to `null` to `Page` (assume also that `Page` returns a motion component)

```jsx
<AnimatePresence exitBeforeEnter>
  <Suspense fallback={null}>
    <Page {...pageProps} key={router.asPath}/>
  </Suspense>
</AnimatePresence>
```

**Comment by Viqueer** [comment] 2022-08-17 14:54
I guess I now understand why my exit animations for my fallback component were not working

**Comment by dumbravaandrei22** [comment] 2022-11-20 22:21
Hello, I think I have the same problem. I am trying to use AnimatePresence in order to make some route navigation transitions using NextJs 13. NextJs 13 is now using Suspense and my AnimatePresence parent will wrap the NextJs tree:
(my AnimatePresence is in the layout.tsx).

<img width="562" alt="image" src="https://user-images.githubusercontent.com/14004579/202929234-3ba1faed-4393-4ec2-9921-f134487cba67.png">


In my case, the component (page) that is about to be unmounted is not "frozen". The children (the new page) updates in both components. The old page (that is about to be unmounted) should be completely frozen.

**Comment by samypogs** [comment] 2023-01-15 18:26
@dumbravaandrei22 Im also experiencing this problem. Did you find any solution or workaround to this?

**Comment by dumbravaandrei22** [comment] 2023-01-16 19:28
hey @samypogs 
Yes, I did.

I used react-freeze and usePresence order to accomplish this.
My code under the AnimatePresence looks like this:

`
import { Freeze } from 'react-freeze';
....
const [isPresent, safeToRemove] = usePresence();
....
<motion.main
      id={id}
      ref={mainRef}
      {...mainFp}
      onAnimationStart={() => {
        // react-freeze adds an inline display none, so on animation start I removed it.
        if(!isPresent) {
          mainRef.current.getElementsByTagName('div')[0].style = '';
        }
      }}
      onAnimationComplete={() => {
        if(!isPresent) {
          safeToRemove();
        }
      }}
      className={styles.container}
    >
      <Freeze freeze={!isPresent}>
        <div>
          {children}
        </div>
      </Freeze>
    </motion.main>`

**Comment by dumbravaandrei22** [comment] 2023-01-16 19:32
But this is just a workaround. AnimatePresence shows know how to handle this case.
So the issue is still persisting.

**Comment by james-william-r** [comment] 2023-05-27 21:19
Also interested in achieving this! 🙋

**Comment by joevingracien** [comment] 2023-05-27 22:23
Would be lovely to be able to natively do that :)

**Comment by vimtor** [comment] 2023-06-01 09:41
This would be amazing!

**Comment by tomaszbryndzia** [comment] 2023-07-27 08:46
Error still occurs. I tried [dumbravaandrei22](https://github.com/dumbravaandrei22) solution but still fails. 

`The server could not finish this Suspense boundary, likely due to an error during server rendering. Switched to client rendering.`

Main Component
` return (
    <AnimatePresence initial={false}>
      {isOpen && (
        <Child animation={animation} classes={classes} key="something">
          {children}
        </Child>
      )}
    </AnimatePresence>
  );`
  
  Child Component
  `const Child = ({ animation, classes, children }) => {
  const [isPresent, safeToRemove] = usePresence();

  return (
    <motion.div
      {...animation}
      transition={{ duration: 0.2 }} // Duration of the animation (in seconds)
      className={classes}
      onAnimationComplete={() => {
        if (!isPresent) safeToRemove();
      }}
    >
      <Freeze freeze={!isPresent}>
        <div>{children}</div>
      </Freeze>
    </motion.div>
  );
};`

**Comment by pongells** [comment] 2023-10-11 13:53
@dumbravaandrei22 and @tomaszbryndzia -- could you create an example of your workaround in action? 

does it replace using <Suspense>?

**Comment by michael-mashush** [comment] 2023-10-27 13:33
I'm new, but I tried to solve the same problem, maybe it's not exactly the same, but I like this solution:

1. FallbackComponent:

`const Fallback: React.FunctionComponent<TestProps> = (props) => {

  React.useEffect(() => {
    props.onMount()
    return () => {
      setTimeout(props.onUnmount, 500)
    }
  }, [])

  return null

}`

2. RoutingManager component:

`const PageManager: React.FunctionComponent = () => {

  const [ isLoading, setIsLoading ] = React.useState<boolean>(true)

  function startLoading(): void {
    setIsLoading(true)
  }

  function endLoading(): void {
    setIsLoading(false)
  }

  useRedirectToInitialPage()
  
  const {
    actualRoutes,
    redirectPath,
    redirectFrom
  } = useAppRoutingInformation()

  return (
    <React.Fragment>
      <FullscreenLoader
        isVisible={isLoading}
        message="Загружаем необходимые данные, пожалуйста, подождите."
      />
      <AnimatePresence initial={false} mode="wait">
        <React.Suspense fallback={(
          <Fallback 
            onMount={startLoading} 
            onUnmount={endLoading}
          />
        )}>
          <Routes>
            <Route Component={Wrapper}>
              {actualRoutes.map((route) => (
                <Route 
                  key={route.path} 
                  {...route} 
                />
              ))}
              <Route 
                path="*" 
                element={ <Navigate to={redirectPath} state={{from: redirectFrom}} /> }
              />
            </Route>
          </Routes>
        </React.Suspense>
      </AnimatePresence>
    </React.Fragment>
  )

}`

3. FullscreenLoader component:

`const FullscreenLoader: React.FunctionComponent<Props> = (props) => {
  
  return (
    <AnimatePresence initial={false}>
      {props.isVisible && (
        <LoaderBackdrop>
          <LoaderContent message={props.message} />
        </LoaderBackdrop>
      )}
    </AnimatePresence>
  )

}

export default FullscreenLoader`

**Comment by michael-mashush** [comment] 2023-10-27 13:44
I'm a newbie, faced the same problem and tried to solve it like this. The FullscreenLoader component appears suddenly to hide the content of an unloaded page, but disappears smoothly.

1. Fallback component:

```typescript
type FallbackProps = {
  onMount: () => void
  onUnmount: () => void
}

const Fallback: React.FunctionComponent<FallbackProps> = (props) => {

  React.useEffect(() => {
    props.onMount()
    return () => {
      setTimeout(props.onUnmount, 1000)
    }
  }, [])

  return null

}
``` 

2. PageManager component:

```typescript
const PageManager: React.FunctionComponent = () => {

  const [ isLoading, setIsLoading ] = React.useState<boolean>(true)

  function startLoading(): void {
    setIsLoading(true)
  }

  function endLoading(): void {
    setIsLoading(false)
  }

  useRedirectToInitialPage()
  
  const {
    actualRoutes,
    redirectPath,
    redirectFrom
  } = useAppRoutingInformation()

  return (
    <React.Fragment>
      <FullscreenLoader
        isVisible={isLoading}
        message="Загружаем необходимые данные, пожалуйста, подождите."
      />
      <AnimatePresence initial={false} mode="wait">
        <React.Suspense fallback={(
          <Fallback 
            onMount={startLoading} 
            onUnmount={endLoading}
          />
        )}>
          <Routes>
            <Route Component={Wrapper}>
              {actualRoutes.map((route) => (
                <Route 
                  key={route.path} 
                  path={route.path}
                  Component={route.Component}
                />
              ))}
              <Route 
                path="*" 
                element={ <Navigate to={redirectPath} state={{from: redirectFrom}} /> }
              />
            </Route>
          </Routes>
        </React.Suspense>
      </AnimatePresence>
    </React.Fragment>
  )

}
``` 

3. FullscreenLoader component:

```typescript
const FullscreenLoader: React.FunctionComponent<Props> = (props) => {
  
  return (
    <AnimatePresence initial={false}>
      {props.isVisible && (
        <LoaderBackdrop>
          <LoaderContent message={props.message} />
        </LoaderBackdrop>
      )}
    </AnimatePresence>
  )

}
```

**Comment by lpic10** [comment] 2023-11-17 10:53
I have here a working example using context: [codesandbox](https://codesandbox.io/p/sandbox/green-http-hy3yvq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp2gh7su000a356aubivbg0m%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp2gh7su0003356aus7jeyn2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp2gh7su0007356a8ply7wsn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp2gh7su0009356ankr852a3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B43.445289554936366%252C56.554710445063634%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp2gh7su0003356aus7jeyn2%2522%253A%257B%2522id%2522%253A%2522clp2gh7su0003356aus7jeyn2%2522%252C%2522activeTabId%2522%253A%2522clp2goe7003c8356a09jfl1fp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp2gh7su0002356a30k7tr34%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522id%2522%253A%2522clp2ghmvx004q356aiplxmwip%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.tsx%2522%252C%2522id%2522%253A%2522clp2glltp029q356avy2w0gfh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FBackdropContext.tsx%2522%252C%2522id%2522%253A%2522clp2gnndt037y356aaw05k60e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FBackdrop.tsx%2522%252C%2522id%2522%253A%2522clp2goe7003c8356a09jfl1fp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FMyComponent.tsx%2522%252C%2522id%2522%253A%2522clp2guyao04nt356ajuxfvq8g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clp2hmmvi0c3v356aqacajys9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clp2gh7su0009356ankr852a3%2522%253A%257B%2522id%2522%253A%2522clp2gh7su0009356ankr852a3%2522%252C%2522activeTabId%2522%253A%2522clp2hmxih0c8h356a97q6k3tk%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clp2hmxih0c8h356a97q6k3tk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clp2gh7su0007356a8ply7wsn%2522%253A%257B%2522id%2522%253A%2522clp2gh7su0007356a8ply7wsn%2522%252C%2522activeTabId%2522%253A%2522clp2gh7su0004356aaklhnvc2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp2gh7su0004356aaklhnvc2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clp2gh7su0005356amoicdip7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522preview%2522%252C%2522id%2522%253A%2522clp2hg78z09k7356aokcnntbs%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by mattgperry** [comment] 2024-01-02 16:12
Closing this as a `wontfix`

I just had a spike on this. My general approach, if anyone wants to take a stab, is to have a component with the same sig as `Suspense` i.e 

```jsx
<AnimateSuspense fallback={fallback}>{children}</AnimateSuspense>
```

This contained a `Suspense` component that was provided `children` but instead of providing `fallback` we provide one that just contains an effect that fires when the component unmounts. This sets some state that removes the user-provided `fallback` which we've been provided by the user.

However it didn't work too well, the to fundamental issues being how do we conditionally not render `fallback` if the `children` `Promise` doesn't throw? And how do we know if it throws in the future? This makes it ok to animate children when its first mounted but the expectation would be that its `exit` prop works too, and I couldn't get that working either.

**Closed by mattgperry** 2024-01-02 16:12 UTC
Labels: feature, wontfix
