### ISSUE TITLE
[BUG] REGRESSION: Drag and layout animation broken when page is being scrolled

### ISSUE THREAD

**Issue by buesing** [framer/motion#1240] opened 2021-08-18 17:26 UTC
**2. Describe the bug**

**This used to work in version 4.1.11**: https://codesandbox.io/s/framer-motion-2-drag-to-reorder-forked-hboo3?file=/src/App.js
Open the code sandbox, scroll down and drag the elements vertically. Notice the glitchy jumping around during drag start. If you change the framer version to 4.1.11, this will work again. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**
See above

**4. Steps to reproduce**

1. Go to https://codesandbox.io/s/framer-motion-2-drag-to-reorder-forked-hboo3?file=/src/App.js
2. Scroll down to see the white boxes
3. Drag one of them up or down
4. Notice the box moving to places it's not supposed to

**5. Expected behavior**

Boxes should be smoothly draggable like here https://codesandbox.io/s/fc4rt?file=/src/App.js

**Comment by buesing** [comment] 2021-08-19 06:40
I just determined that this regression was introduced in version 4.1.12. Version 4.1.11 still works as expected.

**Comment by vavra7** [comment] 2021-08-22 11:55
I also just encountered the bug when i tried to build [App Store-style card expansion](https://codesandbox.io/s/app-store-ui-using-react-and-framer-motion-ecgc2) example referred in [examples page](https://www.framer.com/docs/examples/) which is impossible to make it work due to this issue.

Here is my reproduction of the bug:
https://codesandbox.io/s/framer-motion-drag-with-layoutid-bug-u4m0w

According to my observation the **cause of corrupted dragging is property `layoutId`**. When you remove it layout animation is gone but dragging works correctly.

> I just determined that this regression was introduced in version 4.1.12. Version 4.1.11 still works as expected.

This is not true for my example. Problem is also in version 4.1.11.

**Comment by jlevy-io** [comment] 2021-08-23 03:25
@buesing - I can confirm that rolling back to 4.1.11 has removed the issue for me

**Comment by buesing** [comment] 2021-08-23 07:29
> This is not true for my example. Problem is also in version 4.1.11.

@vavra7 I just tried your example with 4.1.11 and it worked for me. Are you sure?

**Comment by vavra7** [comment] 2021-08-23 08:44
> > This is not true for my example. Problem is also in version 4.1.11.
> 
> @vavra7 I just tried your example with 4.1.11 and it worked for me. Are you sure?

I tested it silly for version ^4.1.11 instead of 4.1.11  so I had still 4.1.17. My apologize and I also confirm that rollback to 4.1.11 works.

**Comment by mattgperry** [comment] 2021-11-24 09:05
Closing as this demo has been replaced with the `Reorder` components.

**Closed by mattgperry** 2021-11-24 09:05 UTC
Labels: bug

**Comment by buesing** [comment] 2021-11-24 09:28
@mattgperry I'm not sure which demo you're referring to, the demos I can find by googling `drag to reorder framer motion` still use the `drag` prop. But in any case, that doesn't fix the underlying issue I believe? I'd think this issue can also cause problems in other use cases than reordering. The issue above clearly demonstrates that a regression has been introduced in 4.1.12, or am I missing something?

**Comment by mattgperry** [comment] 2021-11-24 10:56
Any drag to reorder implementation was based on a demo I made a while ago. We only support drag to reorder via the Reorder components.
