### ISSUE TITLE
[BUG] transform-origin miscalculation in Firefox

### ISSUE THREAD

**Issue by gajus** [framer/motion#824] opened 2020-10-22 00:09 UTC
**1. Read the [FAQs](#faqs) 👇**

Done

**2. Describe the bug**

framer miscalculates transform-origin and there is no way to override it.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/example-2-simple-translation-forked-kgdj9?file=/src/index.js

**4. Steps to reproduce**

Inspect `rect` element styles.

**5. Expected behavior**

Expected (Chrome):

```js
element {
    transform: scale(1) rotate(360deg);
    transform-origin: 0.5px 0.5px;
}

```

Unexpected (Firefox)

```js
element {
    transform: scale(1) rotate(360deg);
    transform-origin: 0px 0px 0px;
}

```

**Comment by KirdesMF** [comment] 2020-12-17 00:34
you can override it with `originX` `originY` in the style prop

**Comment by gajus** [comment] 2020-12-18 14:35
Can you please update sandbox example to show how? Because I was not able to.

**Comment by KirdesMF** [comment] 2020-12-18 16:48
https://codesandbox.io/s/example-2-simple-translation-forked-18sm3?file=/src/index.js

**Comment by gajus** [comment] 2020-12-23 23:09
That is odd. Thank you. I am sure I've tried it, but must have messed up something. I might accidentally tried setting `{x, y}` instead, now that I think about it more.

The underlying issue still exists, but this workaround works.

**Comment by mattgperry** [comment] 2021-01-29 08:26
For my later reference: Firefox probably hasn't measured element properly (it has issues doing this on mount)

**Comment by mattgperry** [comment] 2022-06-02 11:48
This seems to be fixed in Firefox in the meantime

**Closed by mattgperry** 2022-06-02 11:48 UTC
Labels: bug

**Comment by pheki** [comment] 2024-08-06 01:18
Also for future reference:

I can reproduce this same issue on a specific setup on Firefox 128 and Chromium 127 (recent versions), framer-motion 4.1.17 (released on 2021-05-17). If I remove and re-add the component, it works correctly.

I don't have a minimal reproducible example though and I haven't tested more recent versions of `framer-motion`.
