### ISSUE TITLE
[BUG] Layout animations don't work properly in sticky containers

### ISSUE THREAD

**Issue by two-legs** [framer/motion#1535] opened 2022-05-20 08:57 UTC
**1. Describe the bug**
I have Reorder layout in sticky container (also it can be reproduced in fixed container). When I mix items reordering and main page scroll reorder animation is broking sometimes. 

Seems like layout projection for stuck elements uses window scroll in calculations but it shouldn't be done for fixed or stuck elements. 

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

https://codesandbox.io/s/framer-motion-5-drag-to-reorder-lists-forked-q9cixq

**4. Steps to reproduce**

1. Reorder items
2. Scroll page 
3. Repeat

**5. Expected behavior**

There shouldn't be animation glitches

**6. Video or screenshots**

https://user-images.githubusercontent.com/9340251/169492501-b38a84e2-c5b6-4c1f-a8a6-928d19d8079b.mov

**7. Environment details**
macOS 12.3 
Chrome 101.0.4951.64 (Official Build) (arm64)

**Comment by mattgperry** [comment] 2022-06-01 12:57
In the next couple weeks I want to introduce a prop which will allow us to tag elements that are position sticky/fixed and account for this in the layout animations, so hopefully we can find a fix for this soon

**Comment by equinusocio** [comment] 2022-06-09 06:56
Same issue here, but more visible. Here a reproduction site:

0. The header is sticky via CSS
1. [Go here](https://staging.design.wonderflow.ai/documentation/release-notes) and scroll down
2. Change to playground page from the top nav
3. You see the highlight element is animated from the bottom

This happens only if there page (body) scrolled.

**Comment by pie6k** [comment] 2022-06-14 13:13
@mattgperry is any workaround possible in the meanwhile?

**Comment by isc30** [comment] 2022-06-21 09:18
I believe its possible to go up the DOM using `getComputedStyle` and the first css `position` that is set is the actual one. This way we wouldn't need a specific prop to mark this case.

For example if I have a reusable component with a layout animation inside, the application developer can use it and add `position: sticky`. How would they pass the new prop to the nested `motion.div`?

If we can detect this case automatically, its a massive win

**Comment by mattgperry** [comment] 2022-06-21 09:50
@isc30 But then you'd have to, for every node involved in the layout animation, traverse up the tree and hit `getComputedStyle`. The will be performance implications there that have to be looked at as without some consideration to mitigate/optimise this it wouldn't scale well.

**Comment by isc30** [comment] 2022-06-21 10:04
agreed, performance will need to be optimized. If I remember well `getComputedStyle` is a proxy object and only gets evaluated when accessing one of the props in it. This would only be called when the `motion.div` itself re-renders.

**Comment by equinusocio** [comment] 2022-06-27 07:44
Any ETA for a release with this fix?

**Comment by EricSSartorius** [comment] 2022-07-26 00:03
I'm coming across the same issue, is this still being looked into?
 A tab nav element is animating fine on pages that don't have a sticky header but the animation flies in from all over the place on certain pages that do have an adjacent header element with position sticky. (Currently using version 6.5.1)

**Comment by tillschweneker** [comment] 2022-09-23 15:00
> I'm coming across the same issue, is this still being looked into? A tab nav element is animating fine on pages that don't have a sticky header but the animation flies in from all over the place on certain pages that do have an adjacent header element with position sticky. (Currently using version 6.5.1)

Same here. The issue still persists in 7.3.6. Is there any workaround or fix for this?

**Comment by equinusocio** [comment] 2022-09-26 08:28
> > I'm coming across the same issue, is this still being looked into? A tab nav element is animating fine on pages that don't have a sticky header but the animation flies in from all over the place on certain pages that do have an adjacent header element with position sticky. (Currently using version 6.5.1)
> 
> Same here. The issue still persists in 7.3.6. Is there any workaround or fix for this?

The only way i found is to switch from sticky to fixed, unfortunately.

**Comment by Aroagilbo** [comment] 2022-09-30 08:04
This is also affecting BlokLondon, see context thread: https://framer-team.slack.com/archives/C01B14R6E22/p1664460678005719

The fixed position workaround works, I'll try to explain it to them

**Comment by mattgperry** [comment] 2022-12-05 10:59
Can people give this fix a go, adding `layout` and `layoutRoot` props to `sticky` elements.

Animations won't run on these components but should fix layout animations of all children.

**Comment by equinusocio** [comment] 2022-12-05 12:42
> Can people give this fix a go, adding `layout` and `layoutRoot` props to `sticky` elements.
> 
> 
> 
> Animations won't run on these components but should fix layout animations of all children.

Can't find doc about them, are they just boolean?

**Comment by mattgperry** [comment] 2023-01-13 13:40
@equinusocio Ah it's true, I think that PR got lost in a waterfall of layout animation PRs at the time. I'll look into digging it out next week.

**Comment by mattgperry** [comment] 2023-01-18 16:11
`layoutRoot` published in `8.5.0` https://codesandbox.io/s/framer-motion-2-layout-animations-forked-gc4ckn?file=/src/App.js

**Comment by TmLev** [comment] 2023-01-18 17:28
It resolved my issue, thank you so much!

**Comment by equinusocio** [comment] 2023-01-19 12:27
@mattgperry Any update about adding them to the doc too?

**Comment by mattgperry** [comment] 2023-01-30 10:33
I've just added it to a couple FAQs in the layout animations documentation under new questions asking about `position: sticky` and also in elements where surrounding content changes.

**Closed by mattgperry** 2023-01-30 10:33 UTC
Labels: bug

**Comment by fredericoo** [comment] 2023-02-07 13:55
Just reporting this is not working as expected for me. on `9.0.2`

**Comment by rajbirjohar** [comment] 2023-03-19 23:26
Bumping. It does not work for me either. Pretty simple use case too. I have a sticky side navigation with an absolutely positioned indicator div lying behind the current active link. If I scroll down the page and attempt to switch to a different page, it will animate from the bottom of the view port.

**Comment by MafinBoy** [comment] 2023-03-28 08:35
> Bumping. It does not work for me either. Pretty simple use case too. I have a sticky side navigation with an absolutely positioned indicator div lying behind the current active link (its within the link html itself so it can fill up the container of the link if that matters, so not a direct child but a sub child). If I scroll down the page and attempt to switch to a different page, it will animate from the bottom of the view port.
> 
> Edit: https://codesandbox.io/p/sandbox/practical-johnson-ldxio2?file=%2Fcomponents%2FSidebar.tsx
> 
> Hope this helps.

I have the exact same issue, but additionally after adding `layoutRoot` and when using multiple `layoutId`'s when one of them ***is animating*** and the other one ***starts to animate*** the first one is kind of lagging.
As you can see on the video below, the hover element (grey box) and the active link element (blue bar) are moving fine by their own, but when both of them move at the same time, the blue bar starts lagging.

https://user-images.githubusercontent.com/42269909/228176745-493db819-7f1e-448e-a662-4687f8f09a60.mov

**Comment by 05akalan57** [comment] 2023-06-02 21:50
```jsx
'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useState } from 'react'

import { motion } from 'framer-motion'

export default function FlowLayout({ children }) {
  const tabs = [
    { label: 'Keşfet', path: '/flow' },
    { label: 'Takipler', path: '/flow/follows' },
    { label: 'Popüler', path: '/flow/popular' },
    { label: 'Yeniler', path: '/flow/new' }
  ]

  const pathname = usePathname()
  const [activeTab, setActiveTab] = useState(pathname)

  return (
    <>
      <motion.div
        className="sticky top-0 z-10 flex select-none border-b border-neutral-800 bg-neutral-900"
        layoutRoot
        layout
      >
        {tabs.map((tab, i) => (
          <Link key={i} href={tab.path} onClick={() => setActiveTab(tab.path)}>
            <div
              className={`relative rounded-full px-4 py-4 transition-all ${
                activeTab !== tab.path && 'hover:text-neutral-400'
              }`}
            >
              {tab.label}
              {activeTab === tab.path && (
                <motion.div
                  layout
                  className="absolute inset-0 z-10 my-2 rounded-lg bg-white mix-blend-difference"
                  layoutId="motion"
                  transition={{
                    type: 'spring',
                    bounce: 0.2,
                    duration: 0.6
                  }}
                />
              )}
            </div>
          </Link>
        ))}
      </motion.div>
      {children}
    </>
  )
}
```

**Comment by equinusocio** [comment] 2023-06-03 05:46
Yes same. Is not fixed or is hard to understand

**Comment by qqharry21** [comment] 2023-06-09 16:58
I have the same issue here.

**Used**
"framer-motion": "^10.12.16"
_

https://github.com/framer/motion/assets/48307775/b992c993-b40a-420f-b443-38f815e07f8a

**Comment by ouwargui** [comment] 2023-06-28 04:51
It's not working, neither with `position: fixed` or with `position: sticky`

**Comment by leandronorcio** [comment] 2023-08-04 13:21
> Bumping. It does not work for me either. Pretty simple use case too. I have a sticky side navigation with an absolutely positioned indicator div lying behind the current active link (its within the link html itself so it can fill up the container of the link if that matters, so not a direct child but a sub child). If I scroll down the page and attempt to switch to a different page, it will animate from the bottom of the view port.
> 
> Edit: https://codesandbox.io/p/sandbox/practical-johnson-ldxio2?file=%2Fcomponents%2FSidebar.tsx
> 
> Hope this helps.

I have the exact same issue, did you find any workaround?

**Comment by rajbirjohar** [comment] 2023-08-04 22:23
> > Bumping. It does not work for me either. Pretty simple use case too. I have a sticky side navigation with an absolutely positioned indicator div lying behind the current active link (its within the link html itself so it can fill up the container of the link if that matters, so not a direct child but a sub child). If I scroll down the page and attempt to switch to a different page, it will animate from the bottom of the view port.
> > Edit: https://codesandbox.io/p/sandbox/practical-johnson-ldxio2?file=%2Fcomponents%2FSidebar.tsx
> > Hope this helps.
> 
> I have the exact same issue, did you find any workaround?

@leandronorcio No lol. Totally ignored. My hacky solution was to set the wrapping div with `overflow: hidden` so that the slide up isn't as noticeable. It will still do that but because of `overflow: hidden`, it will at least be covered up momentarily until it reaches the desired position.

**Comment by equinusocio** [comment] 2023-08-05 12:27
@mattgperry guess this issue should be reopened since there is clearly something not working here.

**Comment by fredericoo** [comment] 2023-08-05 12:55
> @mattgperry guess this issue should be reopened since there is clearly something not working here. 

tried flagging it on discord and twitter and was [quickly dismissed as not a priority](https://twitter.com/fredoiq/status/1673990623072772098?s=46&t=HxoJgQOBijIHQwi6F6qRvQ) (and as if it's me who can't do it lol)

**Comment by pakxe** [comment] 2023-08-18 16:50
@05akalan57

**Comment by Yoshintame** [comment] 2023-08-21 12:05
I have exactly the same problem as @05akalan57. Nobody came up with a solution?

**Comment by 05akalan57** [comment] 2023-08-23 13:27
> I have exactly the same problem as @05akalan57. Nobody came up with a solution?

No, I couldn't find any solution. Unfortunately, I gave up on using Framer for tab transitions. 😔️

**Comment by fredericoo** [comment] 2023-09-04 16:07
> Using `layoutRoot` prop worked for me. However, I had to use it on all child elements too:
> 
> ```js
> // ❌ Doesn't work
> <motion.div layout layoutRoot>
>    <motion.div layout />
> </motion.div layout layoutRoot>
> ```
> 
> ```js
> // ✅ Works
> <motion.div layout layoutRoot>
>    <motion.div layout layoutRoot />
> </motion.div layout layoutRoot>
> ```

oh nice! glad you made it work but it makes no sense, how come multiple layout roots? and did you add the props to the closing tag as well???? HAHAHA

**Comment by ShahriarKh** [comment] 2023-09-04 17:14
> oh nice! glad you made it work but it makes no sense, how come multiple layout roots? 

I didn't get that deep to see what is really causing the problem. I just added `layoutRoot` to children and saw it worked. I also noticed that some transitions are not working after that, and adding a simple `tranisiton: all 0.2s` in css fixed it. But, I say again that I didn't investigate too much and it stills feel "hacky" to me; just posted here, wishing it can help others.

> and did you add the props to the closing tag as well???? HAHAHA

I noticed that something is wrong with my JSX, but... Anyways, edited it... 😬😂

**Comment by konsalex** [comment] 2023-09-16 21:31
Experiencing the same problem 🥲 Also it's just not convenient to add a `layout` prop to all the children imho, as a nav header will maybe have quite some levels of nesting till a segmented view component

**Comment by tossivahva** [comment] 2024-01-19 14:00
@qqharry21 @05akalan57 any solutions? I have exactly the same problem? Can't figure it out even with Copilot xD

**Comment by vsl-dev** [comment] 2024-03-09 13:37
> I'm having the same issue.
> 
> **Used** "framer-motion": "^10.12.10",
> 
> ```js
> 'use client'
> 
> import Link from 'next/link'
> import { usePathname } from 'next/navigation'
> import { useState } from 'react'
> 
> import { motion } from 'framer-motion'
> 
> export default function FlowLayout({ children }) {
>   const tabs = [
>     { label: 'Keşfet', path: '/flow' },
>     { label: 'Takipler', path: '/flow/follows' },
>     { label: 'Popüler', path: '/flow/popular' },
>     { label: 'Yeniler', path: '/flow/new' }
>   ]
> 
>   const pathname = usePathname()
>   const [activeTab, setActiveTab] = useState(pathname)
> 
>   return (
>     <>
>       <motion.div
>         className="sticky top-0 z-10 flex select-none border-b border-neutral-800 bg-neutral-900"
>         layoutRoot
>         layout
>       >
>         {tabs.map((tab, i) => (
>           <Link key={i} href={tab.path} onClick={() => setActiveTab(tab.path)}>
>             <div
>               className={`relative rounded-full px-4 py-4 transition-all ${
>                 activeTab !== tab.path && 'hover:text-neutral-400'
>               }`}
>             >
>               {tab.label}
>               {activeTab === tab.path && (
>                 <motion.div
>                   className="absolute inset-0 z-10 my-2 rounded-lg bg-white mix-blend-difference"
>                   layoutId="motion"
>                   layout
>                   transition={{
>                     type: 'spring',
>                     bounce: 0.2,
>                     duration: 0.6
>                   }}
>                 />
>               )}
>             </div>
>           </Link>
>         ))}
>       </motion.div>
>       {children}
>     </>
>   )
> }
> ```
> 
>  simplescreenrecorder-2023-06-03_00.48.21.mp4

Çözüm buldunmu bendede aynı sorun yaşanıyor
