### ISSUE TITLE
[FEATURE] onDragOver

### ISSUE THREAD

**Issue by siddharthkp** [framer/motion#538] opened 2020-05-11 06:59 UTC
**2. Describe the bug**

`onDragOver` of an element is not fired when a `motion.div` is dragged over the element. This works for native elements.

Repro: https://codesandbox.io/s/nostalgic-mendel-xmijk?file=/src/App.js:944-976

Bigger context: Implementing a drag and drop with framer-motion

**4. Steps to reproduce**

1. Drag the motion.div (blue) over "bucket" - nothing happens
2. Drag the div without motion (grey) over "bucket" - fires onDragOver

**5. Expected behavior**

Both should fire onDragOver events.

**7. Environment details**

Chrome Version 80 on Mac OS Mojave 10.14.6

**Comment by ultd** [comment] 2020-06-07 15:48
any progress on this?

**Comment by siddharthkp** [comment] 2020-06-10 10:12
I talked to @InventingWithMonster, this is a constraint of the implementation detail. It's not a _bug_ in the implementation detail

This can be changed from _bug_ to _feature request_

**Comment by ultd** [comment] 2020-06-25 00:10
Hello any update on Magic Motion bounding box stuff into the core DOM renderer?

**Comment by jamwise** [comment] 2021-08-05 19:42
@mattgperry any updates on this? We're hoping to use Framer Motion for a project but there doesn't seem to be any way to detect drag over. If this isn't yet set up are there any workarounds that would help?

**Comment by WeersProductions** [comment] 2021-11-02 17:57
@mattgperry Is there any way to do drag *and drop* on another element at the moment? Seems to be related to the aforementioned `onDragOver` event, but I was wondering whether there is already a way to do this (or do we know of an example that implements drag and drop on elements)?

**Comment by zw13p** [comment] 2022-01-31 11:58
What's the status on this? This "Magic Motion bounding box", any news on that and how would it help solve this issue?

Honestly I think this should be classified as a bug (and hence treated with priority :) )
As written on the website on motion components: "These work exactly like their static counterparts, but offer props that allow you to: [..]" So they do not work exactly as their static counterparts as it breaks existing standard functionally.

Also the problem is bigger than onDragOver: onDrop and onDragEnter also do not work and possibly more. (Right now I am interested most in onDrop)

So what to do now if I want to implement dropping? I've been digging for solutions, the best seems to be to manually keep track of coordinates of "droppable" components, and when the drag ends, match the current cursor coordinate with these known coordinates. However this feels like a major leap backwards. What's your advice on this? 

If I can somehow be of help for implementing/testing, please reach out to me directly. Thanks a bunch!

**Comment by anki247** [comment] 2022-03-18 15:58
Meanwhile a workaround I use:
- As soon you start dragging set the `pointer-events: none` of the drag element
- on the dropzone the events `mouseenter` and `mouseleave` will now fire, which enables you the possibility 😁
Hope this helps

**Comment by mattgperry** [comment] 2022-03-18 17:46
This is still a feature request and still not a priority. It’s most likely to happen if we need it in Framer, but we are talking months not weeks. Obviously we would also accept a PR if this is pressing for you.

**Comment by maxphillipsdev** [comment] 2022-03-23 10:54
Bumpity bump 👀

**Comment by mattgperry** [comment] 2022-03-23 11:12
@maxphillipsdev the last update on this was five days ago and unfortunately I prioritise feature requests on in reverse “bumpity bump” order

**Comment by tpict** [comment] 2022-04-14 20:38
This would be really helpful for complex reordering–presumably we could render some elements as drag targets with `onDragEnter` instead of manually checking for position overlap (which works great for 2D reordering).

I'm interested in writing a PR for this, but it would be good to get some conversation going about how this would work.

It seems that native `ondragenter` is fired when the mouse pointer enters the element's bounding rect, which isn't ideal. It feels much nicer to fire drag enter events on "is the dragged element's center within the target bounds?". This is what the `Reorder` component does. Do we want to enforce that behavior, even if it differs from the native equivalent?

Are simultaneous drag events on different elements supported? I'm not super clued in to touch gestures.

**Comment by maxphillipsdev** [comment] 2022-04-15 05:28
@tpict I think it would be helpful to have both as an option. I agree with the earlier comments in this thread that the default behaviour should be to check if the mouse pointer is over the bounds of the drop target as it is with the native HTML `drag` option (also why this issue should be treated as a bug imo). That said, I agree with you that it does feel nicer to have it fire the drag enter event based on the bounding box overlap rather than the pointer position, and this would be nice as an additional option. The default I think should be to keep parity with the native HTML properties though.

**Comment by tpict** [comment] 2022-04-21 18:32
I think this is a deceivingly challenging feature to implement in a way that
1. scales well to many drop targets
2. works universally without modifying element styles

These can be accomplished per-app where you can fudge things a bit to make it work nicely. For example:

In my case, the drop targets have an invisible layer above them with a higher z-index than the dragged item. When the drag gesture begins, the invisible targets are offset by the distance between the cursor and the center of the dragged item. To the user, it appears that the dragged item triggers a `dragover` event when the item's center enters the drop target. Since it uses native pointer events instead of Framer's layout measurements, it scales very well. 

However, it's no silver bullet for this ticket. framer-motion inserting elements into the DOM behind closed curtains will probably cause grief in certain scenarios.

**Comment by SyntheticDesigner** [comment] 2022-05-31 22:07
I cant wait to see this type of feature built into Framer motion. After implementing a few different drag and drop solutions and having each solution involve using completely different methods I definitely could see this difficulty in this. Like [tpict](https://github.com/tpict) said creating an implementation that is scalable and universal is the key here not to mention making it mesh with the entire Framer motion library. I honestly cant imagine the scope. If this comes to pass Framer motion really will be a one stop shop for anything animation. Good luck Matt looking forward to the next update with or without onDragOver.

**Comment by RyanLarge13** [comment] 2023-12-23 19:06
> Meanwhile a workaround I use:
> 
> * As soon you start dragging set the `pointer-events: none` of the drag element
> * on the dropzone the events `mouseenter` and `mouseleave` will now fire, which enables you the possibility 😁
>   Hope this helps

@anki247 Thank you for this reply! So helpful and a great way to think out of the box regardless of if it is just a work around. This was a great way for me to track state when a user wants to move a folder into another in a new file management system I am creating with Electron Vite and Framer Motion

Regarding this discussion being under features I think it would be a good idea to move this under issues. For DND functionality to be complete these DND eventsshould be included within the library and working. Unpopular opinion. Lets bump up the priority of implementing this feature and respect for those working on this library.

**Comment by mattgperry** [comment] 2024-01-02 14:26
I'm labelling as `wontfix` and closing to set expectations.

It's still possible that this feature will be added in the future but it will only be if we need to add this functionality into Framer which IMO would still be around a year away.

**Closed by mattgperry** 2024-01-02 14:26 UTC
Labels: feature

**Comment by Abuladze7** [comment] 2024-02-21 08:10
any updates?
