### ISSUE TITLE
[FEATURE] Objects with drag enable prevent page scroll

### ISSUE THREAD

**Issue by cesarvarela** [framer/motion#458] opened 2020-02-07 23:27 UTC
I'm using this for a horizontally draggable object that covers the entire width of the device,  and this works beautifully, but seems to disable the natural touch scroll of the page, when touching said object

**Comment by FlorinSenoner** [comment] 2020-02-11 20:56
Duplicate of #429

**Comment by mattgperry** [comment] 2021-02-19 16:53
This has been fixed since

**Closed by mattgperry** 2021-02-19 16:53 UTC
Labels: feature

**Comment by denishotii** [comment] 2024-03-12 14:20
@mattgperry can you please explain to me where exactly this has been fixed? Because I just ran into the same problem!

The element with drag, doesn't allow me to scroll the page! (On touch screen devices).
