### ISSUE TITLE
[BUG] State updates interrupting animations

### ISSUE THREAD

**Issue by adhenrique** [framer/motion#1374] opened 2021-11-30 16:05 UTC
**Describe the bug**

My app has a plans table page, which contains a component that request API data (aka container). The API responds with an array of items and I use setState() hook to store the items in the component’s state.
So I iterate through state items and call another component to show plan cards at each iterate.

When the cards enter the screen, the animation does not take place, the animation does not consider stagger or any configs defined.

**CodeSandbox reproduction of the bug**
[https://codesandbox.io/s/priceless-davinci-jw7p7](https://codesandbox.io/s/priceless-davinci-jw7p7)

At the top of the page, there is a menu with two links: `With api request` and `Without api request (fixed data)`

The first link is the page where the bug occurs.
The second link is a page similar to the first. The difference here is that the data is fixed in the component state, and animation works good

**Steps to reproduce**
1. Go to [https://codesandbox.io/s/priceless-davinci-jw7p7](https://codesandbox.io/s/priceless-davinci-jw7p7)
2. Wait to api responds (the animation does not work)
3. Click in second link and see animation working
4. Now, click to first link again...

**Expected behavior**

When finish the API request, the animation should occur as in the second codesandbox link

**Video or screenshots**
![Sandbox - CodeSandbox](https://user-images.githubusercontent.com/11527271/144081753-936f63cd-0019-4b77-b36b-29513f2cbfa0.gif)

**Environment details**

MacOS Mojave;
Chrome 96

App:
Next JS 10
Material ui 4.11
Framer motion 4.1.18 (I also tested it with version 4.1.17, 5.0.0 and 5.3.3)

**Comment by adhenrique** [comment] 2021-11-30 16:08
I updated the codesandbox, and added a third link with setTimeout into useEffect (simulating API request)

**Comment by adhenrique** [comment] 2021-11-30 16:08
related #1085 (?)

**Comment by mattgperry** [comment] 2023-01-04 15:50
I believe this is a dupe of https://github.com/framer/motion/issues/776

**Comment by mattgperry** [comment] 2023-01-04 15:51
In the meantime, as stagger is applied by animations instigated by the parent (which here is happening before children are rendered), it is possible to set your own on children via `delay`

**Closed by mattgperry** 2023-01-04 15:51 UTC
Labels: bug
