### ISSUE TITLE
[BUG] Layout prop children stretching in mobile browsers

### ISSUE THREAD

**Issue by MartinRybergLaude** [framer/motion#1372] opened 2021-11-29 21:24 UTC
**1. Read the [FAQs](#faqs) 👇**

Done.

**2. Describe the bug**

In the documentation, visual stretching of children of an element with "layout" prop set are expected to stretch unless the direct children bear the layout prop as well. This works as expected in desktop browsers, but in mobile browsers, a stretch, sometimes permanent, still happens under certain conditions.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

[https://codesandbox.io/s/framer-motion-5-layout-prop-behavior-eezf8?file=/src/App.tsx](https://codesandbox.io/s/framer-motion-5-layout-prop-behavior-eezf8?file=/src/App.tsx)

**4. Steps to reproduce**

1. Open sandbox in mobile browser (chrome and firefox on android tested)
2. Press "search" button

**5. Expected behavior**

Expecting no stretching of children to occur. When entering the input field and pressing enter on the mobile keyboard, expected behaviour is shown. Only the search button causes issues here. 

**6. Video or screenshots**
Current behavior:
![2021-11-29 22 17 25](https://user-images.githubusercontent.com/32536904/143944329-be5ed836-7869-4c3c-a448-06106d0a22aa.jpg)
Expected behavior:
![2021-11-29 22 17 16](https://user-images.githubusercontent.com/32536904/143944341-815bf583-11bc-4c07-a195-676d5482307d.jpg)

**7. Environment details**

Android 12, Chrome 96 and Firefox 94

**Comment by sebqq** [comment] 2021-12-10 07:06
Actually, I get this kind of error a lot even in web browser with v5. Had to remove some layout animations completely as I wasn't able to do something about it.

**Comment by tpict** [comment] 2022-03-01 15:05
I'm seeing something similar with `layout="position"` in a CSS grid: when a layout change occurs that would increase the height of a `min-content` row, the existing elements in that row are scaled in the Y-axis inversely proportional to the change in height.

**Comment by mattgperry** [comment] 2024-01-03 10:04
Can't reproduce in latest Safari so closing for now.

**Closed by mattgperry** 2024-01-03 10:04 UTC
Labels: bug
