### ISSUE TITLE
[BUG] Timed Animation pauses running on inactive tabs

### ISSUE THREAD

**Issue by ckruppe** [framer/motion#501] opened 2020-04-02 11:09 UTC
An timed animation with and explicit duration and tween type is pausing on inactive tabs and plays on the same position after the tab gets active.

CodeSandbox example:
https://codesandbox.io/s/animations-tmfz1

1. Go to the CodeSandbox link
2. Wait till the animation starts.
3. Switch tab mid animation.
4. Switch back after some seconds.
5. Animation plays from the state there you leaved the tab.

Expected behavior:
I would expect the animation to run in time with the actual time passed. So if i start an 30 seconds animation and i leave the tab, i expect the animation state at 20 seconds if i come back after 20 seconds. (Or at least i would expect an option to force this behavior)

**Comment by tribakzero** [comment] 2020-05-01 15:29
Can confirm, but in my case, I'm using staggerChildren and the animated elements that were expected to transition while inactive are bundled up and looks like they are no more one element but are moving together.

**Comment by polarisdigitech** [comment] 2020-07-24 08:07
I think the issue is with how the browser handles javascript on inactive tabs. I think the browser pauses execution of javascript on inactive tabs to reduce battery consumption.

**Comment by InventingWithMonster** [comment] 2020-07-24 08:53
Yeah this is the underlying issue. I'll see if there's a way to fast
forward these animations when the tab is resumed.

**Comment by ckruppe** [comment] 2020-08-03 09:51
We did it with some browser API's. I will try to provide some example but. Its overall more complicated to achieve this from outside your library.

**Comment by AlexandrKolesnikov** [comment] 2020-12-24 11:02
Hey guys! First of all, thank you for the amazing solution for animations.
Is there any progress regarding how to avoid this pause while the browser pauses javascript evaluation on tab focus loss?

**Comment by ckruppe** [comment] 2021-01-11 10:02
Oh look... i totally forgot to provide our Solution here. What we did was that we did setup "manual controls" for the animation and stopped it on visibility change of the tab. After we got visibility back wie startet the animation again but from an starting point where the animation would be if it was running in background.

Example: 
`
class Example extends Component {
    constructor(props) {
        super(props);

        this.controls = new AnimationControls();
    }
    componentDidMount() {
        this.controls.mount();
        document.addEventListener('visibilitychange', this.visibilityChangeHandler);
    }
    componentWillUnmount() {
        document.removeEventListener('visibilitychange', this.visibilityChangeHandler);
    }
    ...
    visibilityChangeHandler() {
        if (document.hidden) {
            this.controls.stop();
        } else {
            this.controls.set({width: SET TO WIDTH IT WOULD BE TO THIS TIME IN THE ANIMATION});
            this.startAnimation();
        }
    }
    startAnimation() {
        this.controls.start({
            transition: {
                duration: CALCULATE THE DURATION IT HAS TO RUN TILL COMPLETION,
                ease: 'linear',
                type: 'tween'
            },
            width: '100%'
        });
    }
    render() {
        return (
            <Progress
                animate={this.controls}
                initial={{width: 0}}
            />
    }
}
`
Its highly specialized so it will need some changes for different use cases.
Also its an class based solution but should be easy to write in function components also.

**Comment by mattgperry** [comment] 2021-01-11 10:08
That looks great, I wonder if it's something I can just write into
`framesync` to ensure the next frame gets flushed with the correct
timestamp instead of the one provided by `requestAnimationFrame`

**Comment by ckruppe** [comment] 2021-01-11 10:17
It would be really cool if you get it implemented in the library itself. :)

But may i suggest to make it optional? I have seen some framer-motion animations that rely on the fact that they stop and resume on tab change in the last few months. So maybe better not break those implementations.

**Comment by 3lijah** [comment] 2021-04-29 21:18
Hello!
I'm having a similar issue with this but it's related to animations with `delay` and `repeatDelay`.

When the `document.visibilityState` becomes `hidden`, all the animation timers continue, but the animations don't start. When the `document.visibilityState` becomes `visible`, the animations all start at the same time.

It would be great if these `setTimeout` timers could all be paused if possible.

Great library by the way!

**Comment by tommhuth** [comment] 2021-06-30 07:33
@3lijah  i'm having similar issue, but in my case the repeat animations get their delay time messed out and the animations  gets all scrambled.

**Comment by milosjovancevic** [comment] 2022-05-30 11:16
Any updates on this?
I also face this issue when tab is inactive, my animation stops and 'waits' for tab to be focused in order to continue.
I need it to run regardless if my tab is focused or not.
Thanks

**Comment by mattgperry** [comment] 2022-06-01 14:48
No updates. I don't think this is a priority for us but maybe now websites are being made with Motion we might get some feature requests. I was just looking into it now, for me I think a bigger problem is the usage of `setTimeout` for `delay` which yeah would break if we tab back. Perhaps a first thing would be to move this to composable `delay` animation.

I'd like to see an example of an animation where adding this by default would break it. I can't imagine one. My more immediate concern is that a value's velocity is currently calculated incorporating framerate but if an animation finished on a frame calculated after switching tabs the framerate would be super unusual and we could see some springs feeding from one animation into the next really bizarrely. But I suppose this would result in less velocity rather than more which would be much more acceptable.

**Comment by mattgperry** [comment] 2022-08-17 14:22
I'm closing this out as I'm looking into adding Motion One into Framer Motion and as that's built on WAAPI we'll probably just defer to doing it however each browser chooses to implement this.

**Closed by mattgperry** 2022-08-17 14:22 UTC
Labels: bug, wontfix

**Comment by patorjk** [comment] 2025-04-11 20:53
I'm running into this issue while using `AnimatePresence`. The animations are preventing the app from transitioning off its loading screen, so the underlying data isn't fetched until the tab becomes active. One hacky solution seems to be writing a wrapper around `AnimatePresence` and then not rendering it if the tab isn't active. Is this the best way to handle this?
