### ISSUE TITLE
How to smooth Framer Motion animation triggered by Mouse Move?

### ISSUE THREAD

**Issue by 1known-x** [framer/motion#2394] opened 2023-11-08 08:06 UTC
I'm working on a project that needs to resize a box on mouse dragging, but I'm having some issues while trying to add animations using Framer Motion.

I've tried 2 different approaches so far.

Using `useState` to handle box params:
```ts
import { useState, type MouseEvent as ReactMouseEvent } from 'react'
import { motion } from 'framer-motion'

const STEP_SIZE = 40;

export default function App() {
  console.log('render')
  const [params, setParams] = useState({ top: 0, height: 0 })

  const handlerMouseDown = (e: ReactMouseEvent<HTMLDivElement>) => {
    const initialPosition = e.clientY
    const handlerMouseMove = (e: MouseEvent) => {
      const movement = e.clientY - initialPosition
      const steps = Math.ceil(Math.abs(movement) / STEP_SIZE)
      setParams({
        top: movement > 0 ? initialPosition : initialPosition - steps * STEP_SIZE,
        height: steps * STEP_SIZE
      })
    }

    const handlerMouseUp = () => {
      window.removeEventListener('mousemove', handlerMouseMove)
      window.removeEventListener('mouseup', handlerMouseUp)
    }

    window.addEventListener('mousemove', handlerMouseMove)
    window.addEventListener('mouseup', handlerMouseUp)
  }

  return (
    <div className="Container" onMouseDown={handlerMouseDown}>
      <motion.div className="Selector" animate={{ top: params.top, height: params.height }}></motion.div>
    </div>
  );
}
```
[CodeSandbox](https://codesandbox.io/s/frosty-hugle-2yzpcg?file=/src/App.tsx:23-1177)

Using `useAnimation` to avoid re-renders:
```ts
import { type MouseEvent as ReactMouseEvent } from 'react'
import { motion, useAnimation } from 'framer-motion'

const STEP_SIZE = 40;

export default function App() {
  console.log('render')
  const controls = useAnimation()

  const handlerMouseDown = (e: ReactMouseEvent<HTMLDivElement>) => {
    const initialPosition = e.clientY
    const handlerMouseMove = (e: MouseEvent) => {
      const movement = e.clientY - initialPosition
      const steps = Math.ceil(Math.abs(movement) / STEP_SIZE)
      controls.start({ // <- change "start" to "set" for no lag but without animation
        top: movement > 0 ? initialPosition : initialPosition - steps * STEP_SIZE,
        height: steps * STEP_SIZE
      })
    }

    const handlerMouseUp = () => {
      window.removeEventListener('mousemove', handlerMouseMove)
      window.removeEventListener('mouseup', handlerMouseUp)
    }

    window.addEventListener('mousemove', handlerMouseMove)
    window.addEventListener('mouseup', handlerMouseUp)
  }

  return (
    <div className="Container" onMouseDown={handlerMouseDown}>
      <motion.div className="Selector" animate={controls}></motion.div>
    </div>
  );
}
```
[CodeSandbox](https://codesandbox.io/s/sparkling-violet-p45ysl?file=/src/App.tsx)

As you can see, `useState`'s approach looks great, but it triggers a re-render every time I move the mouse. On the other hand, `useAnimation`'s approach doesn't re-render, but it looks really bad: the animation freezes a bit if I move the mouse while it's playing. I can use `set` instead of `start`, but I want it to be animated.

Is there anyway to make it looks smoothly while avoiding re-renders?

**Comment by mattgperry** [comment] 2024-01-05 14:43
Essentially a dupe of https://github.com/framer/motion/issues/2088 - animation should work

**Closed by mattgperry** 2024-01-05 14:43 UTC
