### ISSUE TITLE
[BUG] framer-motion/dom v11.3.0+ requires React in non-React projects, despite optional peer dependency

### ISSUE THREAD

**Issue by MickaelOth** [framer/motion#2726] opened 2024-07-14 10:51 UTC
**1. Read the [FAQs](#faqs) 👇**
✅

**2. Describe the bug**

Since version 11.3.0, `framer-motion/dom`, for non-React projects (Vue.js in my case), appears to **require** `react` to be installed, which was not the case for version 11.2.14 and below.

**3. IMPORTANT: Provide a CodeSandbox reproduction of the bug**

`framer-motion@11.2.14` (working) - [https://codesandbox.io/p/devbox/framer-motion-11-2-14-mm8hj3?file=/src/App.vue](https://codesandbox.io/p/devbox/framer-motion-11-2-14-mm8hj3?file=/src/App.vue)
`framer-motion@11.3.2` (not working) - [https://codesandbox.io/p/devbox/framer-motion-11-3-2-wqgsk7?file=/src/App.vue](https://codesandbox.io/p/devbox/framer-motion-11-3-2-wqgsk7?file=/src/App.vue)

**4. Steps to reproduce**

1. Import and use `framer-motion/dom` on a project **without** `react` installed.
2. With `framer-motion@11.2.14` or earlier, the project works without issues (open the first CodeSandbox).
3. Upgrade to `framer-motion@11.3.0` or later (open the second CodeSandbox).
4. Run the project and open the browser console (F12).
5. Observe the error: `Error: Could not resolve "react" imported by "framer-motion". Is it installed?`.
![Observe the error: `Error: Could not resolve "react" imported by "framer-motion". Is it installed?`](https://i.imgur.com/U8VHi9E.png)

**5. Expected behavior**

`framer-motion@11.3.2` should be importable without `react` since `react` is listed as an optional peer dependency.

**Comment by mattgperry** [comment] 2024-07-16 12:47
Thanks for the report! A fix for this is going out in `11.3.5`

**Comment by mattgperry** [comment] 2024-07-17 08:28
That's out now, your sandboxes are private so I can't verify but let me know if that fixes it for you

**Comment by MickaelOth** [comment] 2024-07-17 11:55
> That's out now, your sandboxes are private so I can't verify but let me know if that fixes it for you

Sorry, the sandboxes should be public now.

I'm still facing the issue with the latest version (`11.3.5`)

**Comment by mattgperry** [comment] 2024-07-23 07:49
Strange that it rolls this into the bundled `framer-motion` package, acknowledging it's an optional package, but there aren't any references to React in there otherwise.

```
// optional-peer-dep:__vite-optional-peer-dep:react:framer-motion
throw new Error(`Could not resolve "react" imported by "framer-motion". Is it installed?`);
```

**Comment by MickaelOth** [comment] 2024-07-23 12:07
Indeed, it's strange. I looked at it a bit, I may have something.

The culprit could be the `add-will-change` file, which follows this import path:

1. `dom-entry` imports `animate`
2. `animate` imports `animateTarget` from `visual-element-target`
3. `animateTarget` use `addValueToWillChange` function, from `add-will-change` added in `v11.3.0`,
4. `add-will-change` imports `WillChangeMotionValue`
5. `WillChangeMotionValue` imports `useConstant`
6. `useConstant` finally imports `react`

**Comment by mattgperry** [comment] 2024-07-23 13:19
Ah great find, thanks. That's gotta be it. I'm just doing a publish and will take a look at this after.

**Closed** 2024-07-23 13:35 UTC
Labels: bug

**Comment by mattgperry** [comment] 2024-07-23 13:46
I've published as `11.3.11`, let me know if that doesn't fix that for you.

**Comment by mattgperry** [comment] 2025-02-03 13:44
@roybarber can you try `12.0.9`? I'm actively working to fix this but it doesn't show up in local builds so it's difficult to see why it's being included. Even here https://cdn.jsdelivr.net/npm/motion@12.0.9/+esm you can see the first thing is a completely useless `import"/npm/react@19.0.0/+esm";` 😕

**Comment by roybarber** [comment] 2025-02-03 17:44
@mattgperry i could probably knock up a quick repo that reproduces. 

Funny enough if i remove another package that had a optional dependancy of v16 react thats the only time this breaks. 

If i install react via npm as a dev dependancy that fixes it too, but ive not checked the bundles to see if it then scoops react in

**Comment by roybarber** [comment] 2025-02-03 17:50
@mattgperry  looking at the build i think i've found the issue:

https://github.com/motiondivision/motion/blob/ac626f52878f1e9b877e2db19d84134df4e3e49b/packages/motion/rollup.config.mjs#L128

React is marked as an external dependency for your ES build. In your ES config you’ve defined: 
`external: ['react', 'react-dom', 'react/jsx-runtime'],`

Because React is listed in the external array, Rollup leaves any imports for it untouched in the output rather than bundling React into your file. When jsDelivr serves your bundle, it rewrites the bare module specifier (in this case, 'react') to a full URL—in your output you see it as:

`import '/npm/react@19.0.0/+esm'`

This rewrite is performed by jsDelivr so that the consumer of your module can load React from the CDN. Essentially, nothing in your build script “adds” this line—the fact that React appears as the first import is just Rollup preserving the external dependency, and jsDelivr rewriting that import to its CDN URL.

**Comment by mattgperry** [comment] 2025-02-03 18:08
@roybarber Can you check 12.0.11?
