### ISSUE TITLE
[FEATURE]: add `"use client"` directives

### ISSUE THREAD

**Issue by juliusmarminge** [framer/motion#2054] opened 2023-03-27 17:03 UTC
**Is your feature request related to a problem? Please describe.**

Today, when I want to use `framer-motion` I need to export a bunch of wrappers internally if I want to use it in Server Components, i.e. 

```ts
"use client";
export { motion } from "framer-motion";
```

This is quite annoying and creates a bunch of "junk" in user land.

**Describe the solution you'd like**

Framer to add the `"use client"` directive to all their components (and hooks?) so that consumers can just use the components in server components directly

**Describe alternatives you've considered**

Keep as is, let the developer create all the necessary "re-exports" themselves.

**Additional context**

I saw some issues about Next 13 and RSC but most of them were bug reports - which this isn't. Re-exporting as shown above does work but it'd be nice if this was done in the library itself.

Not sure if there are any bundle complications?

**Comment by mattgperry** [comment] 2023-03-28 08:27
Allegedly we can just add this to the main export but needs some work in the Rollup config not to ditch this

**Comment by juliusmarminge** [comment] 2023-03-31 08:41
Seems like that doesn't quite work :/ I think the directives must be on the underlying mechanisms which use interactivity. `'use client';` on the main entrypoint gives a new error:

![CleanShot 2023-03-31 at 10 39 59](https://user-images.githubusercontent.com/51714798/229070977-63abeddb-21e6-45cc-8aef-be8eef28a6e1.png)

**Comment by juliusmarminge** [comment] 2023-03-31 08:57
The way I have it on my project is like this

```ts
// app/use-client.tsx (stuff that needs to be wrapped)
"use client";

import { motion } from "framer-motion";

export const MotionDiv = motion.div;
```

**Comment by switz** [comment] 2023-05-16 19:20
doing this for now:

Lib/motion.ts
```javascript
'use client';

import { motion } from 'framer-motion';

export const tr = motion.tr;
```

then to use:
```javascript
import * as motion from 'Lib/motion'

<motion.tr />
```

**Comment by wherewith** [comment] 2023-06-09 17:29
> doing this for now:
> 
> Lib/motion.ts
> 
> ```js
> 'use client';
> 
> import { motion } from 'framer-motion';
> 
> export const tr = motion.tr;
> ```
> 
> then to use:
> 
> ```js
> import * as motion from 'Lib/motion'
> 
> <motion.tr />
> ```

Thanks!

**Comment by apfelbox** [comment] 2023-06-22 19:12
We just had a related (?) issue, that in code that basically looks like this:

```typescript
const value = useMotionValue(0);
const transformed = useTransform(value, ...);

useEffect(() => 
{
	value.set(10);
}, []);
```

The transform is not updated.
Adding a `useMotionValueEvent(value, "change")` there works, and doing a

```typescript
window.setTimeout(() => value.set(10), 50);
```

in the effect works as well, but not the base one.
I can't reproduce it in a CodeSandbox, however our app is a Next.js app with the App Router, so it might be RSC related.

**Comment by janjachacz** [comment] 2023-08-24 14:49
> doing this for now:
> 
> Lib/motion.ts
> 
> ```js
> 'use client';
> 
> import { motion } from 'framer-motion';
> 
> export const tr = motion.tr;
> ```
> 
> then to use:
> 
> ```js
> import * as motion from 'Lib/motion'
> 
> <motion.tr />
> ```

This way would import the whole `Lib/motion` and prevent tree-shaking.
I'd prefer @juliusmarminge's [way](https://github.com/framer/motion/issues/2054#issuecomment-1491568547)

**Comment by juliusmarminge** [comment] 2023-08-24 15:03
`import *` is treeshakeable by most modern bundlers

**Comment by T-J-D-Cavey** [comment] 2023-12-06 13:50
Is this 'user client' solution specific for 'react server componenats'?

I'm getting 'getStaticPaths is not a function' error just using vanilla Next.js in dev server. Despite framer motion saying it's compatible with SSG

**Comment by mattgperry** [comment] 2024-01-04 15:27
Closing this issue as a `wontfix` to set expectations I won't personally be looking at this however I would accept a PR that implements it.

**Closed by mattgperry** 2024-01-04 15:27 UTC
Labels: feature
